"use client";
import { useEffect,useMemo,useState,type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { AlertCircle,CheckCircle2,CornerUpLeft,FileText,Send,ShieldCheck,XCircle } from "lucide-react";
import { requestConfirmation } from "@/components/in-app-confirmation";
import { PayeeDetailsReveal } from "@/components/payee-details-reveal";
import type { ExecutiveRequest,ExecutivePendingPayment,ExecutiveHistory } from "@/lib/procureflow/approver-executive-data";

type Decision="approve"|"reject"|"return";
type Msg={type:"success"|"error";text:string}|null;
const money=(v:unknown,c="NGN")=>{try{return new Intl.NumberFormat("en-NG",{style:"currency",currency:c,maximumFractionDigits:2}).format(Number(v||0));}catch{return `${c} ${Number(v||0).toLocaleString("en-NG")}`;}};
const dt=(v:unknown)=>{if(!v)return "—";const d=new Date(String(v));return Number.isNaN(d.getTime())?String(v):d.toLocaleString("en-NG");};
const date=(v:unknown)=>{if(!v)return "—";const d=new Date(String(v));return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString("en-NG",{day:"2-digit",month:"short",year:"numeric"});};

function Section({title,meta,children}:{title:string;meta?:string;children:ReactNode}){return <section className="approver-detail-section"><div className="approver-detail-section-head"><strong>{title}</strong>{meta?<span>{meta}</span>:null}</div>{children}</section>;}

function useOpenEvent(name:string,setId:(id:number)=>void){
  useEffect(()=>{const h=(e:Event)=>{const id=Number((e as CustomEvent)?.detail?.requestId||0);if(id>0)setId(id);};window.addEventListener(name,h);return()=>window.removeEventListener(name,h);},[name,setId]);
}

function RequestDetail({requestId}:{requestId:number|null}){
  const [detail,setDetail]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
  useEffect(()=>{let active=true;if(!requestId){setDetail(null);return;}setLoading(true);setError("");
    fetch(`/api/approver/requests/${requestId}`,{cache:"no-store"}).then(async r=>{const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p?.error||"Unable to open request.");if(active)setDetail(p);})
    .catch(e=>{if(active)setError(e instanceof Error?e.message:"Unable to open request.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[requestId]);
  if(!requestId)return <div className="empty-state">Choose a request to view its complete record.</div>;
  if(loading)return <div className="empty-state compact">Opening complete request details…</div>;
  if(error)return <div className="action-message error">{error}</div>;
  const r=detail?.request;if(!r)return null;const p=detail.payee;
  return <div className="approver-full-request-detail">
    <div className="approver-request-hero"><div><span>REQUEST DETAIL</span><h3>{r.request_no}</h3><p>{r.department_project||"No department/project"} · {r.category||"No category"}</p></div><span className="status-pill">{r.status||"—"}</span></div>
    <div className="approver-detail-grid">
      <article><span>Requested by</span><strong>{r.requester_name||"—"}</strong><small>{r.requester_role||"—"}</small></article>
      <article><span>Procurement Manager</span><strong>{r.procurement_manager_name||"—"}</strong></article>
      <article><span>Amount</span><strong>{money(r.estimated_amount)}</strong></article><article><span>Priority</span><strong>{r.priority||"Normal"}</strong></article>
      <article><span>Request date</span><strong>{date(r.request_date)}</strong></article><article><span>Required date</span><strong>{date(r.required_date)}</strong></article>
      <article><span>Payment status</span><strong>{r.payment_status||"Not Ready"}</strong></article><article><span>Next role</span><strong>{r.next_role||"—"}</strong></article>
      <article><span>Approved by</span><strong>{r.approved_by_name||r.approved_by_role||"—"}</strong><small>{r.approved_by_role||""}</small></article>
      <article><span>Approved at</span><strong>{dt(r.approved_at)}</strong></article><article><span>Approval mode</span><strong>{r.approval_mode||"—"}</strong></article>
      <article><span>Last updated</span><strong>{dt(r.updated_at)}</strong></article>
    </div>
    <Section title="Business justification"><p className="approver-long-text">{r.justification||"No justification recorded."}</p></Section>
    <Section title="Line items" meta={`${detail.items?.length||0} item(s)`}>
      {detail.items?.length?<div className="table-wrap"><table className="data-table compact-table"><thead><tr><th>Item / Service</th><th>Description</th><th>Qty</th><th>Unit price</th><th>Total</th><th>Category</th><th>Suggested vendor</th></tr></thead><tbody>{detail.items.map((x:any)=><tr key={x.id}><td><strong>{x.item_name}</strong></td><td>{x.description||"—"}</td><td>{x.quantity}</td><td>{money(x.unit_price)}</td><td>{money(x.total)}</td><td>{x.category||"—"}</td><td>{x.suggested_vendor||"—"}</td></tr>)}</tbody></table></div>:<div className="empty-state compact">No line items attached.</div>}
    </Section>
    <Section title="Payment recipient readiness" meta="Protected information">
      <div className="approver-payee-grid"><span>Recipient known<b>{p?.recipient_known?"Yes":"No"}</b></span><span>Payee<b>{p?.payee_name_masked||"Pending"}</b></span><span>Account name<b>{p?.account_name_masked||"Pending"}</b></span><span>Bank<b>{p?.bank_name_masked||"Pending"}</b></span><span>Account<b>{p?.account_number_masked||"Pending"}</b></span><span>Verification<b>{p?.verification_status||"Pending"}</b></span><span>Readiness<b>{p?.payment_readiness_status||"Pending"}</b></span></div>
      <PayeeDetailsReveal requestId={requestId} available={Boolean(p?.recipient_known)}/>
    </Section>
    <Section title="Request context & messages" meta={`${detail.threadMessages?.length||0} message(s)`}>{detail.threadMessages?.length?<div className="approver-timeline">{detail.threadMessages.map((x:any)=><div key={x.id}><span/><article><strong>{x.sender_name||x.sender_role||"User"}</strong><small>{dt(x.created_at)} · {x.sender_role||"User"}</small><p>{x.message_text}</p></article></div>)}</div>:<div className="empty-state compact">No additional context message.</div>}</Section>
    <Section title="Sourcing & vendor quotes" meta={`${detail.quotes?.length||0} quote(s)`}>
      {detail.sourcing?.map((s:any)=><div className="approver-sourcing-summary" key={s.id}><strong>{s.sourcing_no||`Sourcing #${s.id}`}</strong><span>{s.status||"—"} · Recommended vendor: {s.recommended_vendor_name||"Pending"}</span><p>{s.reason_for_recommendation||"No recommendation note."}</p></div>)}
      {detail.quotes?.length?<div className="table-wrap"><table className="data-table compact-table"><thead><tr><th>Vendor</th><th>Quote</th><th>Delivery</th><th>Terms</th><th>Score</th><th>Recommended</th></tr></thead><tbody>{detail.quotes.map((q:any)=><tr key={q.id}><td>{q.vendor_name||q.registry_vendor_name||"—"}</td><td>{money(q.quoted_amount,q.currency||"NGN")}</td><td>{q.delivery_time_days==null?"—":`${q.delivery_time_days} days`}</td><td>{q.payment_terms||"—"}</td><td>{q.score??"—"}</td><td>{q.is_recommended?"Yes":"No"}</td></tr>)}</tbody></table></div>:<div className="empty-state compact">No vendor quotes attached.</div>}
    </Section>
    <Section title="Purchase orders" meta={`${detail.purchaseOrders?.length||0} PO(s)`}>{detail.purchaseOrders?.length?detail.purchaseOrders.map((po:any)=><article className="approver-linked-record" key={po.id}><div><strong>{po.po_no}</strong><span>{po.vendor_name||"Vendor pending"} · {money(po.total_amount)}</span></div><div><span>{po.status||"—"}</span><small>Payment: {po.payment_status||"—"} · Receiving: {po.receiving_status||"—"}</small></div>{po.items?.length?<div className="table-wrap approver-linked-items"><table className="data-table compact-table"><thead><tr><th>Item</th><th>Qty</th><th>Unit</th><th>Total</th></tr></thead><tbody>{po.items.map((x:any)=><tr key={x.id}><td>{x.item_name}</td><td>{x.quantity}</td><td>{money(x.unit_price)}</td><td>{money(x.total)}</td></tr>)}</tbody></table></div>:null}</article>):<div className="empty-state compact">No purchase order created.</div>}</Section>
    <Section title="Payments" meta={`${detail.payments?.length||0} record(s)`}>{detail.payments?.length?<div className="table-wrap"><table className="data-table compact-table"><thead><tr><th>Payment</th><th>Amount</th><th>Status</th><th>Reference</th><th>Transfer</th><th>Date</th><th>Finance note</th></tr></thead><tbody>{detail.payments.map((x:any)=><tr key={x.id}><td>{x.payment_no}</td><td>{money(x.amount,x.currency||"NGN")}</td><td>{x.status||"—"}</td><td>{x.payment_reference||"—"}</td><td>{x.transfer_type||"—"}</td><td>{date(x.payment_date)}</td><td>{x.finance_note||"—"}</td></tr>)}</tbody></table></div>:<div className="empty-state compact">No payment recorded yet.</div>}</Section>
    <Section title="Receipts / proof of payment" meta={`${detail.receipts?.length||0} record(s)`}>{detail.receipts?.length?<div className="table-wrap"><table className="data-table compact-table"><thead><tr><th>Receipt</th><th>Type</th><th>Amount</th><th>Status</th><th>File</th><th>Date</th></tr></thead><tbody>{detail.receipts.map((x:any)=><tr key={x.id}><td>{x.receipt_no}</td><td>{x.receipt_type||x.payment_method||"—"}</td><td>{money(x.amount,x.currency||"NGN")}</td><td>{x.status||"—"}</td><td>{x.original_file_name||"—"}</td><td>{date(x.created_at)}</td></tr>)}</tbody></table></div>:<div className="empty-state compact">No receipt/proof attached yet.</div>}</Section>
    <Section title="Supporting documents" meta={`${detail.documents?.length||0} document(s)`}>{detail.documents?.length?<div className="table-wrap"><table className="data-table compact-table"><thead><tr><th>Document</th><th>Type</th><th>Status</th><th>Date</th></tr></thead><tbody>{detail.documents.map((x:any)=><tr key={x.id}><td><FileText size={14}/> {x.title||x.file_name}</td><td>{x.document_type||"—"}</td><td>{x.status||"—"}</td><td>{date(x.created_at)}</td></tr>)}</tbody></table></div>:<div className="empty-state compact">No linked supporting document.</div>}</Section>
    <Section title="Approval trail" meta={`${detail.approvals?.length||0} event(s)`}><div className="approver-timeline">{detail.approvals?.map((x:any)=><div key={x.id}><span/><article><strong>{x.action}</strong><small>{dt(x.created_at)} · {x.approved_by_name||x.approved_by_role||"System"}</small><p>{x.status_before||"—"} → {x.status_after||"—"}</p>{x.note||x.reason?<em>{x.note||x.reason}</em>:null}</article></div>)}</div></Section>
    <Section title="Workflow history" meta={`${detail.workflow?.length||0} event(s)`}><div className="approver-timeline">{detail.workflow?.map((x:any)=><div key={x.id}><span/><article><strong>{x.event}</strong><small>{dt(x.created_at)} · {x.user_name||x.user_role||"System"}</small><p>{x.status||"—"}</p>{x.note?<em>{x.note}</em>:null}</article></div>)}</div></Section>
  </div>;
}

function Picker({rows,id,setId,approved=false}:{rows:ExecutiveRequest[];id:number|null;setId:(v:number)=>void;approved?:boolean}){return <div className="approver-executive-picker"><label><span>{approved?"Open approved request":"Open pending request"}</span><select value={id||""} onChange={e=>setId(Number(e.target.value))}><option value="">Select a request…</option>{rows.map(r=><option key={r.id} value={r.id}>{r.requestNo} — {approved?`Approved by ${r.approvedByName||r.approvedByRole||"Unknown"} — `:`${r.requesterRole||"Requester"} — `}{money(r.estimatedAmount)}</option>)}</select></label><small>{rows.length} request{rows.length===1?"":"s"} available.</small></div>;}

export function ApproverPendingRequests({rows}:{rows:ExecutiveRequest[]}){
  const router=useRouter(),[id,setId]=useState<number|null>(rows[0]?.id??null),[note,setNote]=useState(""),[busy,setBusy]=useState<Decision|null>(null),[msg,setMsg]=useState<Msg>(null);
  const selected=useMemo(()=>rows.find(r=>r.id===id)||null,[rows,id]);useOpenEvent("procureflow:open-approver-request",setId);
  useEffect(()=>{if(id&&rows.some(r=>r.id===id))return;setId(rows[0]?.id??null);},[rows,id]);
  async function decide(decision:Decision){if(!selected)return;if((decision==="reject"||decision==="return")&&note.trim().length<4){setMsg({type:"error",text:"Enter a reason before returning or rejecting."});return;}
    const approve=decision==="approve",confirmed=await requestConfirmation({eyebrow:"APPROVER / MD",title:approve?"Approve this request?":decision==="return"?"Return this request for correction?":"Reject this request?",description:approve?`${selected.requestNo} will be approved for payment and routed to Finance.`:`${selected.requestNo} will be updated with your decision.`,reference:selected.requestNo,detail:note.trim()||"The decision will be recorded in the workflow and audit trail.",confirmLabel:approve?"Approve Request":decision==="return"?"Return Request":"Reject Request",tone:approve?"success":decision==="return"?"warning":"danger"});if(!confirmed)return;
    setBusy(decision);setMsg(null);try{const res=await fetch("/api/approver/requests/decision",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:selected.id,decision,note})}),p=await res.json().catch(()=>({}));if(!res.ok)throw new Error(p?.error||"Unable to apply decision.");setMsg({type:"success",text:approve?`${selected.requestNo} approved for payment and routed to Finance.`:"Decision recorded."});setNote("");router.refresh();}catch(e){setMsg({type:"error",text:e instanceof Error?e.message:"Unable to apply decision."});}finally{setBusy(null);}}
  if(!rows.length)return <div className="empty-state">No purchase request is currently awaiting Approver / MD decision.</div>;
  return <div className="approver-executive-workspace"><Picker rows={rows} id={id} setId={setId}/><RequestDetail requestId={id}/>{selected?<section className="approver-executive-decision"><div><ShieldCheck size={18}/><div><strong>Approver / MD decision</strong><span>Use one approval action for every request in this queue, regardless of value. Procurement Manager-originated requests also come here for independent approval.</span></div></div><label><span>Decision note / return or rejection reason</span><textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional for approval. Required for return or rejection."/></label>{msg?<div className={`action-message ${msg.type}`}>{msg.text}</div>:null}<div className="approver-actions"><button className="approver-action approve" disabled={Boolean(busy)} onClick={()=>void decide("approve")}><CheckCircle2 size={16}/>{busy==="approve"?"Approving…":"Approve Request"}</button><button className="approver-action return" disabled={Boolean(busy)} onClick={()=>void decide("return")}><CornerUpLeft size={16}/>Return for Correction</button><button className="approver-action reject" disabled={Boolean(busy)} onClick={()=>void decide("reject")}><XCircle size={16}/>Reject Request</button></div></section>:null}</div>;
}

export function ApproverApprovedRequests({rows}:{rows:ExecutiveRequest[]}){const [id,setId]=useState<number|null>(rows[0]?.id??null);useOpenEvent("procureflow:open-approved-request",setId);useEffect(()=>{if(id&&rows.some(r=>r.id===id))return;setId(rows[0]?.id??null);},[rows,id]);if(!rows.length)return <div className="empty-state">No approved request is available yet.</div>;const r=rows.find(x=>x.id===id);return <div className="approver-executive-workspace"><Picker rows={rows} id={id} setId={setId} approved/>{r?<div className="approver-approved-banner"><CheckCircle2 size={18}/><div><strong>Approved request</strong><span>Approved by {r.approvedByName||r.approvedByRole||"Unknown"} · {money(r.estimatedAmount)} · {date(r.approvedAt)}</span></div></div>:null}<RequestDetail requestId={id}/></div>;}

export function ApproverPendingPayments({rows}:{rows:ExecutivePendingPayment[]}){const router=useRouter(),[id,setId]=useState<number|null>(rows[0]?.id??null),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState<Msg>(null);useOpenEvent("procureflow:open-pending-payment",setId);useEffect(()=>{if(id&&rows.some(r=>r.id===id))return;setId(rows[0]?.id??null);},[rows,id]);const r=rows.find(x=>x.id===id)||null;
  async function remind(){if(!r)return;const ok=await requestConfirmation({eyebrow:"PENDING PAYMENT",title:"Send Finance a payment reminder?",description:`${r.requestNo} is approved but has not been recorded as paid.`,reference:r.requestNo,detail:note.trim()||r.waitingReason,confirmLabel:"Send Reminder",tone:"primary"});if(!ok)return;setBusy(true);setMsg(null);try{const res=await fetch("/api/approver/payment-reminders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:r.id,note})}),p=await res.json().catch(()=>({}));if(!res.ok)throw new Error(p?.error||"Unable to send reminder.");setMsg({type:"success",text:`Reminder sent to Finance for ${r.requestNo}.`});setNote("");router.refresh();}catch(e){setMsg({type:"error",text:e instanceof Error?e.message:"Unable to send reminder."});}finally{setBusy(false);}}
  if(!rows.length)return <div className="empty-state">No approved request is currently waiting for Finance payment.</div>;
  return <div className="approver-executive-workspace"><div className="approver-executive-picker"><label><span>Open pending payment</span><select value={id||""} onChange={e=>setId(Number(e.target.value))}><option value="">Select a request…</option>{rows.map(x=><option key={x.id} value={x.id}>{x.requestNo} — {money(x.amount)} — approved by {x.approvedByName||x.approvedByRole||"Unknown"}</option>)}</select></label></div>{r?<section className="pending-payment-status-card"><div className="pending-payment-heading"><AlertCircle size={18}/><div><strong>{r.requestNo}</strong><span>{money(r.amount)} · approved {date(r.approvedAt)} by {r.approvedByName||r.approvedByRole||"Unknown"}</span></div></div><div className="pending-payment-facts"><span>Request status<b>{r.status||"—"}</b></span><span>Payment status<b>{r.paymentStatus||"—"}</b></span><span>Payee verification<b>{r.payeeVerificationStatus||"Pending"}</b></span><span>Payment readiness<b>{r.paymentReadinessStatus||"Pending"}</b></span><span>Latest payment record<b>{r.latestPaymentStatus||"Not created"}</b></span><span>Last reminder<b>{dt(r.lastReminderAt)}</b></span></div><div className="payment-delay-reason"><AlertCircle size={17}/><div><strong>Why this has not been paid yet</strong><span>{r.waitingReason}</span>{r.lastFinanceActivityAt?<small>Latest Finance activity: {dt(r.lastFinanceActivityAt)}</small>:null}</div></div><label className="payment-reminder-note"><span>Reminder note to Finance</span><textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional context for Finance."/></label>{msg?<div className={`action-message ${msg.type}`}>{msg.text}</div>:null}<button className="payment-reminder-button" disabled={busy} onClick={()=>void remind()}><Send size={16}/>{busy?"Sending…":"Send Reminder to Finance"}</button></section>:null}<RequestDetail requestId={id}/></div>;
}

export function ApproverApprovalHistory({rows}:{rows:ExecutiveHistory[]}){const [id,setId]=useState<number|null>(rows[0]?.id??null),r=rows.find(x=>x.id===id)||null;if(!rows.length)return <div className="empty-state">No Approver / MD decision has been recorded yet.</div>;return <div className="approver-executive-workspace"><div className="approver-executive-picker"><label><span>Open approval-history record</span><select value={id||""} onChange={e=>setId(Number(e.target.value))}><option value="">Select a record…</option>{rows.map(x=><option key={x.id} value={x.id}>{x.requestNo||`${x.entityType} #${x.entityId}`} — {x.action} — {x.approvedByName||x.approvedByRole||"Unknown"} — {x.amount==null?"No request amount":money(x.amount)}</option>)}</select></label></div>{r?<section className="approval-history-summary"><div><CheckCircle2 size={18}/><div><strong>{r.requestNo||`${r.entityType} #${r.entityId}`}</strong><span>{r.action} · {dt(r.createdAt)}</span></div></div><div className="approval-history-grid"><span>Approved / decided by<b>{r.approvedByName||r.approvedByRole||"—"}</b></span><span>Amount<b>{r.amount==null?"—":money(r.amount)}</b></span><span>Status before<b>{r.statusBefore||"—"}</b></span><span>Status after<b>{r.statusAfter||"—"}</b></span><span>Approval mode<b>{r.approvalMode||"—"}</b></span><span>Requester<b>{r.requesterName||"—"}{r.requesterRole?` · ${r.requesterRole}`:""}</b></span></div>{r.note?<p>{r.note}</p>:null}</section>:null}{r?.entityType==="Purchase Request"?<RequestDetail requestId={r.entityId}/>:null}</div>;}
