"use client";
import {useEffect,useMemo,useState,type ReactNode} from "react";
import {CalendarDays,Download,FileJson,FileSpreadsheet,FileText,UserRound,Users} from "lucide-react";

const money=(v:unknown,c="NGN")=>{try{return new Intl.NumberFormat("en-NG",{style:"currency",currency:c,maximumFractionDigits:2}).format(Number(v||0));}catch{return c+" "+Number(v||0).toLocaleString("en-NG");}};
const dt=(v:unknown)=>{if(!v)return "—";const d=new Date(String(v));return Number.isNaN(d.getTime())?String(v):d.toLocaleString("en-NG");};
const day=(v:unknown)=>{if(!v)return "";const d=new Date(String(v));return Number.isNaN(d.getTime())?"":d.toISOString().slice(0,10);};
const range=(v:unknown,f:string,t:string)=>{const d=day(v);return(!f||d>=f)&&(!t||d<=t);};
function Status({children}:{children:ReactNode}){return <span className="auditor-status-pill">{String(children??"—")}</span>}
function Empty({text}:{text:string}){return <div className="auditor-empty">{text}</div>}
function Label({title,children}:{title:string;children:ReactNode}){return <label className="auditor-filter-label"><span>{title}</span>{children}</label>}
function Section({title,meta,children}:{title:string;meta?:string;children:ReactNode}){return <section className="auditor-detail-section"><div className="auditor-detail-section-head"><strong>{title}</strong>{meta?<span>{meta}</span>:null}</div>{children}</section>}
function Exports({id}:{id?:number|null}){const s=id?"&id="+id:"";const b="/api/auditor/transactions/export?";return <div className="auditor-export-buttons"><a href={b+"format=xlsx"+s}><FileSpreadsheet size={15}/>Excel</a><a href={b+"format=pdf"+s}><FileText size={15}/>PDF</a><a href={b+"format=csv"+s}><Download size={15}/>CSV</a><a href={b+"format=json"+s}><FileJson size={15}/>JSON</a></div>}

function TransactionDetail({id}:{id:number|null}){
 const [d,setD]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 useEffect(()=>{let live=true;if(!id){setD(null);return;}setLoading(true);setError("");fetch("/api/auditor/transactions/"+id,{cache:"no-store"}).then(async r=>{const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p?.error||"Unable to open transaction.");if(live)setD(p)}).catch(e=>{if(live)setError(e instanceof Error?e.message:"Unable to open transaction.")}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[id]);
 if(!id)return <Empty text="Choose a transaction to open its complete workflow and evidence."/>;
 if(loading)return <Empty text="Loading complete transaction evidence…"/>;
 if(error)return <div className="auditor-error">{error}</div>;
 const r=d?.request,p=d?.payee;if(!r)return null;
 return <div className="auditor-transaction-detail">
  <div className="auditor-transaction-hero"><div><span>TRANSACTION 360</span><h3>{r.request_no}</h3><p>{r.department_project||"—"} · {r.category||"—"}</p></div><Status>{r.status}</Status></div>
  <div className="auditor-summary-grid"><article><span>Requester</span><strong>{r.requester_name||"—"}</strong><small>{r.requester_role||"—"}</small></article><article><span>Procurement Manager</span><strong>{r.procurement_manager_name||"—"}</strong></article><article><span>Amount</span><strong>{money(r.estimated_amount)}</strong></article><article><span>Priority</span><strong>{r.priority||"—"}</strong></article><article><span>Request date</span><strong>{dt(r.request_date)}</strong></article><article><span>Required date</span><strong>{dt(r.required_date)}</strong></article><article><span>Payment status</span><strong>{r.payment_status||"—"}</strong></article><article><span>Next role</span><strong>{r.next_role||"—"}</strong></article></div>
  <Section title="Business justification"><p className="auditor-long-text">{r.justification||"No justification recorded."}</p></Section>
  <Section title="Line items" meta={String(d.items?.length||0)+" item(s)"}>{d.items?.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Item / Service</th><th>Description</th><th>Qty</th><th>Unit price</th><th>Total</th><th>Category</th><th>Suggested vendor</th></tr></thead><tbody>{d.items.map((x:any)=><tr key={x.id}><td><strong>{x.item_name}</strong></td><td>{x.description||"—"}</td><td>{x.quantity}</td><td>{money(x.unit_price)}</td><td>{money(x.total)}</td><td>{x.category||"—"}</td><td>{x.suggested_vendor||"—"}</td></tr>)}</tbody></table></div>:<Empty text="No line items attached."/>}</Section>
  <Section title="Payment recipient readiness" meta="Masked audit view"><div className="auditor-summary-grid"><article><span>Recipient known</span><strong>{p?.recipient_known?"Yes":"No"}</strong></article><article><span>Payee</span><strong>{p?.payee_name_masked||"Pending"}</strong></article><article><span>Account name</span><strong>{p?.account_name_masked||"Pending"}</strong></article><article><span>Bank</span><strong>{p?.bank_name_masked||"Pending"}</strong></article><article><span>Account</span><strong>{p?.account_number_masked||"Pending"}</strong></article><article><span>Verification</span><strong>{p?.verification_status||"Pending"}</strong></article></div></Section>
  <Section title="Context & messages" meta={String(d.threadMessages?.length||0)+" message(s)"}>{d.threadMessages?.length?<div className="auditor-timeline">{d.threadMessages.map((x:any)=><div key={x.id}><span/><article><strong>{x.sender_name||x.sender_role||"User"}</strong><small>{dt(x.created_at)} · {x.sender_role||"—"}</small><p>{x.message_text}</p></article></div>)}</div>:<Empty text="No contextual messages attached."/>}</Section>
  <Section title="Vendor sourcing & quotations" meta={String(d.quotes?.length||0)+" quote(s)"}>{d.sourcing?.map((s:any)=><article className="auditor-linked-card" key={s.id}><strong>{s.sourcing_no||("Sourcing #"+s.id)}</strong><span>{s.status||"—"} · Recommended: {s.recommended_vendor_name||"Pending"}</span><p>{s.reason_for_recommendation||"No recommendation note."}</p></article>)}{d.quotes?.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Vendor</th><th>Quote</th><th>Delivery</th><th>Terms</th><th>Score</th><th>Recommendation</th></tr></thead><tbody>{d.quotes.map((q:any)=><tr key={q.id}><td>{q.vendor_name||q.registry_vendor_name||"—"}</td><td>{money(q.quoted_amount,q.currency||"NGN")}</td><td>{q.delivery_time_days==null?"—":q.delivery_time_days+" days"}</td><td>{q.payment_terms||"—"}</td><td>{q.score??"—"}</td><td>{q.is_selected?"Selected":q.is_recommended?"Recommended":"—"}</td></tr>)}</tbody></table></div>:null}</Section>
  <Section title="Purchase orders" meta={String(d.purchaseOrders?.length||0)+" PO(s)"}>{d.purchaseOrders?.length?d.purchaseOrders.map((po:any)=><article className="auditor-linked-card" key={po.id}><div className="auditor-linked-card-head"><strong>{po.po_no}</strong><Status>{po.status}</Status></div><span>{po.vendor_name||"Vendor pending"} · {money(po.total_amount)}</span><small>Payment: {po.payment_status||"—"} · Receiving: {po.receiving_status||"—"} · Logistics: {po.logistics_status||"—"}</small>{po.items?.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Item</th><th>Qty</th><th>Unit</th><th>Total</th></tr></thead><tbody>{po.items.map((x:any)=><tr key={x.id}><td>{x.item_name}</td><td>{x.quantity}</td><td>{money(x.unit_price)}</td><td>{money(x.total)}</td></tr>)}</tbody></table></div>:null}</article>):<Empty text="No purchase order created."/>}</Section>
  <Section title="Payments" meta={String(d.payments?.length||0)+" payment(s)"}>{d.payments?.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Payment</th><th>Amount</th><th>Status</th><th>Reference</th><th>Method</th><th>Date</th><th>Finance note</th></tr></thead><tbody>{d.payments.map((x:any)=><tr key={x.id}><td>{x.payment_no}</td><td>{money(x.amount,x.currency||"NGN")}</td><td>{x.status||"—"}</td><td>{x.payment_reference||"—"}</td><td>{x.transfer_type||x.payment_method||"—"}</td><td>{dt(x.payment_date)}</td><td>{x.finance_note||"—"}</td></tr>)}</tbody></table></div>:<Empty text="No payment recorded."/>}</Section>
  <Section title="Receipts / proof" meta={String(d.receipts?.length||0)+" record(s)"}>{d.receipts?.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Receipt</th><th>Type</th><th>Amount</th><th>Status</th><th>File</th><th>Date</th></tr></thead><tbody>{d.receipts.map((x:any)=><tr key={x.id}><td>{x.receipt_no}</td><td>{x.receipt_type||x.payment_method||"—"}</td><td>{money(x.amount,x.currency||"NGN")}</td><td>{x.status||"—"}</td><td>{x.original_file_name||"—"}</td><td>{dt(x.created_at)}</td></tr>)}</tbody></table></div>:<Empty text="No receipt/proof attached."/>}</Section>
  <Section title="Supporting documents" meta={String(d.documents?.length||0)+" document(s)"}>{d.documents?.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Document</th><th>Type</th><th>Status</th><th>Date</th></tr></thead><tbody>{d.documents.map((x:any)=><tr key={x.id}><td>{x.title||x.file_name}</td><td>{x.document_type||"—"}</td><td>{x.status||"—"}</td><td>{dt(x.created_at)}</td></tr>)}</tbody></table></div>:<Empty text="No linked document."/>}</Section>
  <Section title="Approval trail" meta={String(d.approvals?.length||0)+" event(s)"}><div className="auditor-timeline">{d.approvals?.map((x:any)=><div key={x.id}><span/><article><strong>{x.action}</strong><small>{dt(x.created_at)} · {x.approved_by_name||x.approved_by_role||"System"}</small><p>{x.status_before||"—"} → {x.status_after||"—"}</p>{x.note||x.reason?<em>{x.note||x.reason}</em>:null}</article></div>)}</div></Section>
  <Section title="Workflow history" meta={String(d.workflow?.length||0)+" event(s)"}><div className="auditor-timeline">{d.workflow?.map((x:any)=><div key={x.id}><span/><article><strong>{x.event}</strong><small>{dt(x.created_at)} · {x.user_name||x.user_role||"System"}</small><p>{x.status||"—"}</p>{x.note?<em>{x.note}</em>:null}</article></div>)}</div></Section>
 </div>
}

function Transaction360({data}:{data:any}){const rows=data?.requests||[],[id,setId]=useState<number|null>(rows[0]?.id??null);useEffect(()=>{if(id&&rows.some((x:any)=>x.id===id))return;setId(rows[0]?.id??null)},[rows,id]);return <div className="auditor-review-stack"><div className="auditor-toolbar"><div><h3>Transaction 360</h3><p>Open any procurement transaction and inspect its complete workflow and evidence.</p></div><div><span>Download all transactions</span><Exports/></div></div><div className="auditor-picker-row"><Label title="Open transaction"><select value={id||""} onChange={e=>setId(Number(e.target.value)||null)}><option value="">Select transaction…</option>{rows.map((r:any)=><option key={r.id} value={r.id}>{r.requestNo+" — "+(r.category||"No category")+" — "+money(r.amount)+" — "+(r.status||"—")}</option>)}</select></Label>{id?<div><span>Download selected transaction</span><Exports id={id}/></div>:null}</div><TransactionDetail id={id}/></div>}

function RoleActivity({data}:{data:any}){const rows=data?.roleActivities||[],users=data?.user360||[];const [uid,setUid]=useState("all"),[role,setRole]=useState("all"),[action,setAction]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState("");const roles=useMemo(()=>Array.from(new Set(rows.map((r:any)=>r.activityRole||r.userRole).filter(Boolean))).sort(),[rows]);const f=useMemo(()=>rows.filter((r:any)=>(uid==="all"||String(r.userId)===uid)&&(role==="all"||String(r.activityRole||r.userRole)===role)&&(!action||String(r.action||"").toLowerCase().includes(action.toLowerCase()))&&range(r.createdAt,from,to)),[rows,uid,role,action,from,to]);return <div className="auditor-review-stack"><div className="auditor-filter-grid"><Label title="User"><select value={uid} onChange={e=>setUid(e.target.value)}><option value="all">All users</option>{users.map((u:any)=><option key={u.id} value={u.id}>{u.fullName+" — "+u.role+" ("+u.username+")"}</option>)}</select></Label><Label title="Role"><select value={role} onChange={e=>setRole(e.target.value)}><option value="all">All roles</option>{roles.map((x:any)=><option key={x}>{x}</option>)}</select></Label><Label title="Action contains"><input value={action} onChange={e=>setAction(e.target.value)} placeholder="APPROVE, PASSWORD, DRAFT…"/></Label><Label title="From"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Label><Label title="To"><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></Label></div><div className="auditor-result-count"><CalendarDays size={15}/>{f.length} activity record(s)</div>{f.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Time</th><th>User</th><th>Role</th><th>Action</th><th>Entity</th><th>Summary</th><th>Visibility</th></tr></thead><tbody>{f.map((r:any)=><tr key={r.id}><td>{dt(r.createdAt)}</td><td><strong>{r.userName||"System"}</strong><small>{r.username||""}</small></td><td>{r.activityRole||r.userRole||"—"}</td><td>{r.action}</td><td>{r.entityType||"—"} {r.entityId?"#"+r.entityId:""}</td><td>{r.summary||"—"}</td><td>{r.visibility||"—"}</td></tr>)}</tbody></table></div>:<Empty text="No activity matches the selected filters."/>}</div>}

function User360({data}:{data:any}){
 const users=data?.user360||[],acts=data?.roleActivities||[],sessions=data?.sessions||[];
 const [id,setId]=useState<number|null>(users[0]?.id??null),[from,setFrom]=useState(""),[to,setTo]=useState("");
 const u=users.find((x:any)=>x.id===id)||null;
 const baseActs=acts.filter((x:any)=>x.userId===id),baseSessions=sessions.filter((x:any)=>u&&x.username===u.username);
 const a=baseActs.filter((x:any)=>range(x.createdAt,from,to)),ss=baseSessions.filter((x:any)=>range(x.loginAt||x.lastSeenAt,from,to));
 const passwordChanges=a.filter((x:any)=>String(x.action||"").toUpperCase()==="PASSWORD_CHANGE").length;
 const adminPasswordEvents=a.filter((x:any)=>String(x.action||"").toUpperCase().includes("PASSWORD")&&String(x.action||"").toUpperCase()!=="PASSWORD_CHANGE").length;
 const period=from||to ? (from||"Beginning")+" to "+(to||"Today") : "All recorded dates";
 return <div className="auditor-review-stack">
  <div className="auditor-filter-grid">
   <Label title="Open user 360"><select value={id||""} onChange={e=>setId(Number(e.target.value)||null)}><option value="">Select user…</option>{users.map((x:any)=><option key={x.id} value={x.id}>{x.fullName+" — "+x.role+" ("+x.username+")"}</option>)}</select></Label>
   <Label title="From"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Label>
   <Label title="To"><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></Label>
  </div>
  <div className="auditor-result-count"><CalendarDays size={15}/>{period}</div>
  {u?<><div className="auditor-user360-head"><div><UserRound size={20}/><div><strong>{u.fullName}</strong><span>{u.username} · {u.role}</span></div></div><Status>{u.active?"Active":"Inactive"}</Status></div>
  <div className="auditor-summary-grid">
   <article><span>Password changes</span><strong>{passwordChanges}</strong><small>Within selected period</small></article>
   <article><span>Administrative password events</span><strong>{adminPasswordEvents}</strong><small>Within selected period</small></article>
   <article><span>Total activities</span><strong>{a.length}</strong><small>Within selected period</small></article>
   <article><span>Recorded sessions</span><strong>{ss.length}</strong><small>Within selected period</small></article>
   <article><span>Failed logins</span><strong>{u.failedLoginCount}</strong><small>Current account counter</small></article>
   <article><span>Locked</span><strong>{u.locked?"Yes":"No"}</strong></article>
   <article><span>Latest login in period</span><strong>{dt(ss[0]?.loginAt||(!from&&!to?u.lastLoginAt:null))}</strong></article>
   <article><span>Latest activity in period</span><strong>{dt(a[0]?.createdAt||(!from&&!to?u.lastActivityAt:null))}</strong></article>
  </div>
  <Section title="User workflow / activity" meta={a.length+" record(s)"}>{a.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Time</th><th>Role</th><th>Action</th><th>Entity</th><th>Summary</th></tr></thead><tbody>{a.map((r:any)=><tr key={r.id}><td>{dt(r.createdAt)}</td><td>{r.activityRole||r.userRole||"—"}</td><td>{r.action}</td><td>{r.entityType||"—"} {r.entityId?"#"+r.entityId:""}</td><td>{r.summary||"—"}</td></tr>)}</tbody></table></div>:<Empty text="No user activity matches the selected date range."/>}</Section>
  <Section title="Session history" meta={ss.length+" session(s)"}>{ss.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Login</th><th>Logout</th><th>Last seen</th><th>Status</th><th>IP</th><th>Expires</th></tr></thead><tbody>{ss.map((x:any)=><tr key={x.id}><td>{dt(x.loginAt)}</td><td>{dt(x.logoutAt)}</td><td>{dt(x.lastSeenAt)}</td><td>{x.status||"—"}</td><td>{x.ipAddress||"—"}</td><td>{dt(x.expiresAt)}</td></tr>)}</tbody></table></div>:<Empty text="No sessions match the selected date range."/>}</Section></>:<Empty text="Select a user."/>}
 </div>
}

function RequestRecords({data,facilityOnly=false}:{data:any;facilityOnly?:boolean}){
 const all=data?.requests||[];
 const scoped=facilityOnly?all.filter((r:any)=>["Facility Manager","ICT"].includes(String(r.requesterRole||""))||/facility|utility|ict/i.test(String(r.sourceType||""))):all;
 const [from,setFrom]=useState(""),[to,setTo]=useState(""),[status,setStatus]=useState("all");
 const statuses=useMemo(()=>Array.from(new Set(scoped.map((r:any)=>r.status).filter(Boolean))).sort(),[scoped]);
 const rows=useMemo(()=>scoped.filter((r:any)=>(status==="all"||String(r.status||"")===status)&&range(r.requestDate||r.updatedAt,from,to)),[scoped,from,to,status]);
 return <div className="auditor-review-stack">
  <div className="auditor-filter-grid">
   <Label title="From"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Label>
   <Label title="To"><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></Label>
   <Label title="Status"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{statuses.map((x:any)=><option key={x}>{x}</option>)}</select></Label>
  </div>
  <div className="auditor-result-count"><CalendarDays size={15}/>{rows.length} {facilityOnly?"Facility / ICT handoff":"procurement"} record(s)</div>
  {rows.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Request</th><th>Request date</th><th>Requester</th><th>Source</th><th>Department / Project</th><th>Category</th><th>Amount</th><th>Status</th><th>Payment</th><th>Updated</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td><strong>{r.requestNo}</strong></td><td>{dt(r.requestDate)}</td><td>{r.requestedBy||"—"}<small>{r.requesterRole||""}</small></td><td>{r.sourceType||"—"}</td><td>{r.departmentProject||"—"}</td><td>{r.category||"—"}</td><td>{money(r.amount)}</td><td><Status>{r.status||"—"}</Status></td><td>{r.paymentStatus||"—"}</td><td>{dt(r.updatedAt)}</td></tr>)}</tbody></table></div>:<Empty text={facilityOnly?"No Facility / ICT handoff records match the selected date range.":"No procurement records match the selected date range."}/>}
 </div>
}

function ExceptionCentre({data}:{data:any}){const rows=(data?.auditEvents||[]).filter((r:any)=>r.severity==="High"||["Denied","Failure","Warning"].includes(String(r.outcome||""))),actors=Array.from(new Set(rows.map((r:any)=>r.actorUsername||r.actorRole||"System")));const [actor,setActor]=useState("all"),[sev,setSev]=useState("all"),[out,setOut]=useState("all");const ss=Array.from(new Set(rows.map((r:any)=>r.severity||"Normal"))),os=Array.from(new Set(rows.map((r:any)=>r.outcome||"—")));const f=rows.filter((r:any)=>(actor==="all"||String(r.actorUsername||r.actorRole||"System")===actor)&&(sev==="all"||String(r.severity||"Normal")===sev)&&(out==="all"||String(r.outcome||"—")===out));return <div className="auditor-review-stack"><div className="auditor-filter-grid"><Label title="Actor"><select value={actor} onChange={e=>setActor(e.target.value)}><option value="all">All actors</option>{actors.map((x:any)=><option key={x}>{x}</option>)}</select></Label><Label title="Severity"><select value={sev} onChange={e=>setSev(e.target.value)}><option value="all">All severities</option>{ss.map((x:any)=><option key={x}>{x}</option>)}</select></Label><Label title="Outcome"><select value={out} onChange={e=>setOut(e.target.value)}><option value="all">All outcomes</option>{os.map((x:any)=><option key={x}>{x}</option>)}</select></Label></div>{f.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Time</th><th>Actor</th><th>Role</th><th>Action</th><th>Entity</th><th>Outcome</th><th>Severity</th><th>Reason</th></tr></thead><tbody>{f.map((r:any)=><tr key={r.id}><td>{dt(r.occurredAt)}</td><td>{r.actorUsername||"System"}</td><td>{r.actorRole||"—"}</td><td>{r.action}</td><td>{r.entityReference||r.entityType||"—"}</td><td>{r.outcome||"—"}</td><td><Status>{r.severity||"Normal"}</Status></td><td>{r.reason||"—"}</td></tr>)}</tbody></table></div>:<Empty text="No exception matches the selected filters."/>}</div>}

function bucket(r:any){const t=(String(r.action||"")+" "+String(r.after||"")).toLowerCase();if(t.includes("return"))return "Returned for Correction";if(t.includes("sent for procurement review"))return "Sent for Procurement Review";if(t.includes("approv"))return "Approved";return "Other";}
function ApprovalTrail({data,delegated=false}:{data:any;delegated?:boolean}){const all=[...(data?.approvalTrail||[]),...(data?.requestWorkflowTrail||[])].filter((r:any)=>!delegated||(r.source==="approval"&&r.approvalMode&&r.approvalMode!=="Normal Approval Mode"));const [cat,setCat]=useState("Approved"),f=all.filter((r:any)=>cat==="All"||bucket(r)===cat),[key,setKey]=useState("");useEffect(()=>{if(f.some((r:any)=>r.source+":"+r.id===key))return;setKey(f[0]?f[0].source+":"+f[0].id:"")},[cat,all.length,key]);const s=f.find((r:any)=>r.source+":"+r.id===key)||null;return <div className="auditor-review-stack"><div className="auditor-filter-grid"><Label title="Category"><select value={cat} onChange={e=>setCat(e.target.value)}><option>Approved</option><option>Sent for Procurement Review</option><option>Returned for Correction</option><option>All</option></select></Label><Label title={delegated?"Open delegated approval":"Open approval / workflow record"}><select value={key} onChange={e=>setKey(e.target.value)}><option value="">Select record…</option>{f.map((r:any)=><option key={r.source+":"+r.id} value={r.source+":"+r.id}>{r.entityLabel+" — "+(r.category||"No category")+" — "+(r.amount==null?"No amount":money(r.amount))+" — "+bucket(r)}</option>)}</select></Label></div>{s?<><div className="auditor-trail-summary"><div><strong>{s.entityLabel}</strong><span>{s.category||"—"} · {s.amount==null?"—":money(s.amount)}</span></div><Status>{bucket(s)}</Status><div className="auditor-summary-grid"><article><span>Entity</span><strong>{s.entityType}</strong></article><article><span>Actor / approver</span><strong>{s.approvedBy||s.approvedByRole||"System"}</strong></article><article><span>Approval mode</span><strong>{s.approvalMode||"—"}</strong></article><article><span>Time</span><strong>{dt(s.createdAt)}</strong></article></div>{s.note?<p>{s.note}</p>:null}</div>{s.requestId?<TransactionDetail id={s.requestId}/>:<Empty text="This record is not linked to a Purchase Request."/>}</>:<Empty text="No record matches this category."/>}</div>}

function NotificationAudit({data}:{data:any}){const rows=data?.notifications||[],recipients=Array.from(new Set(rows.map((r:any)=>r.userName||r.role||"Unassigned"))).sort();const [state,setState]=useState("all"),[rec,setRec]=useState("all"),[from,setFrom]=useState(""),[to,setTo]=useState("");const f=rows.filter((r:any)=>(state==="all"||(state==="read"&&r.read)||(state==="unread"&&!r.read))&&(rec==="all"||String(r.userName||r.role||"Unassigned")===rec)&&range(r.createdAt,from,to));return <div className="auditor-review-stack"><div className="auditor-filter-grid"><Label title="View"><select value={state} onChange={e=>setState(e.target.value)}><option value="all">View all</option><option value="read">Read</option><option value="unread">Unread</option></select></Label><Label title="Recipient"><select value={rec} onChange={e=>setRec(e.target.value)}><option value="all">All recipients</option>{recipients.map((x:any)=><option key={x}>{x}</option>)}</select></Label><Label title="From"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Label><Label title="To"><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></Label></div><div className="auditor-result-count">{f.length} notification record(s)</div>{f.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Time</th><th>Recipient</th><th>Title</th><th>Entity</th><th>Importance</th><th>State</th><th>Channel</th><th>Section</th></tr></thead><tbody>{f.map((r:any)=><tr key={r.id}><td>{dt(r.createdAt)}</td><td>{r.userName||r.role||"—"}</td><td><strong>{r.title}</strong></td><td>{r.entityType||"—"} {r.entityId?"#"+r.entityId:""}</td><td>{r.importance||"—"}</td><td><Status>{r.read?"Read":"Unread"}</Status></td><td>{r.deliveryChannel||"—"}</td><td>{r.sectionTarget||"—"}</td></tr>)}</tbody></table></div>:<Empty text="No notification matches the selected filters."/>}</div>}

const PLACEHOLDERS=new Set(["ABC Diesel Supply","Prime Office Mart","FixRight Maintenance","XYZ Repairs"]);
function VendorHistory({data}:{data:any}){const rows=(data?.vendors||[]).filter((v:any)=>!PLACEHOLDERS.has(String(v.name||"")));return <div className="auditor-review-stack"><div className="auditor-info-card"><Users size={18}/><div><strong>Vendor history</strong><span>Seed/test placeholder vendors are excluded. Ratings use a 5-point scale.</span></div></div>{rows.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Vendor</th><th>Category</th><th>Status</th><th>Rating</th><th>Orders</th><th>Total spend</th><th>Avg. delivery</th><th>Rejections</th><th>Last purchase</th></tr></thead><tbody>{rows.map((v:any)=><tr key={v.id}><td><strong>{v.name}</strong></td><td>{v.category||"—"}</td><td>{v.status||"—"}</td><td><strong>{v.rating==null?"Not rated":Number(v.rating).toFixed(1)+" / 5"}</strong></td><td>{v.completedOrders||0}</td><td>{money(v.totalSpend||0)}</td><td>{v.averageDeliveryTime==null?"—":v.averageDeliveryTime+" days"}</td><td>{v.rejectionCount||0}</td><td>{dt(v.lastPurchaseDate)}</td></tr>)}</tbody></table></div>:<Empty text="No non-placeholder vendor history is available."/>}</div>}

export function AuditorReviewWorkspace({section,data}:{section:string;data:any}){if(section==="Transaction 360")return <Transaction360 data={data}/>;if(section==="Procurement Records")return <RequestRecords data={data}/>;if(section==="Facility / Utility Handoff Trail")return <RequestRecords data={data} facilityOnly/>;if(section==="Role Activity Mirrors")return <RoleActivity data={data}/>;if(section==="User 360")return <User360 data={data}/>;if(section==="Exception Centre")return <ExceptionCentre data={data}/>;if(section==="Approval Trails")return <ApprovalTrail data={data}/>;if(section==="Delegated Approval Review")return <ApprovalTrail data={data} delegated/>;if(section==="Notification Delivery Audit")return <NotificationAudit data={data}/>;if(section==="Vendor History")return <VendorHistory data={data}/>;return null}
