from __future__ import annotations

from datetime import datetime, timezone
from io import BytesIO
from pathlib import Path

import openpyxl
import pandas as pd

from core.db_backend import normalize_postgres_sql
from core.report_service import build_excel_workbook


def test_runtime_autoincrement_schema_is_postgres_identity():
    sql = normalize_postgres_sql(
        "CREATE TABLE IF NOT EXISTS sample (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT)"
    )
    assert "AUTOINCREMENT" not in sql.upper()
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql.upper()


def test_runtime_boolean_and_json_ddl_are_typed():
    sql = normalize_postgres_sql(
        """CREATE TABLE IF NOT EXISTS notifications (
        id INTEGER PRIMARY KEY AUTOINCREMENT, is_read INTEGER DEFAULT 0, dedupe_key TEXT)"""
    )
    assert "is_read BOOLEAN DEFAULT FALSE" in " ".join(sql.split())

    json_sql = normalize_postgres_sql(
        """CREATE TABLE IF NOT EXISTS audit_logs (
        id INTEGER PRIMARY KEY AUTOINCREMENT, before_values TEXT, after_values TEXT)"""
    )
    compact = " ".join(json_sql.split())
    assert "before_values JSONB" in compact
    assert "after_values JSONB" in compact


def test_legacy_last_insert_rowid_is_translated():
    assert normalize_postgres_sql("SELECT last_insert_rowid()") == "SELECT LASTVAL()"


def test_excel_export_removes_timezone_information():
    frame = pd.DataFrame({
        "created_at": [datetime(2026, 7, 27, 10, 0, tzinfo=timezone.utc)],
        "label": ["ok"],
    })
    blob = build_excel_workbook({"Rows": frame})
    workbook = openpyxl.load_workbook(BytesIO(blob))
    value = workbook["Rows"]["A2"].value
    assert isinstance(value, datetime)
    assert value.tzinfo is None


def test_postgres_audit_immutability_migration_exists():
    sql = Path("migrations/postgresql/005_audit_immutability.sql").read_text(encoding="utf-8")
    assert "BEFORE UPDATE ON audit_events" in sql
    assert "BEFORE DELETE ON audit_events" in sql
