from services.payment_instruction_service import (
    _build_purchase_summary,
    generate_payment_instruction_pdf,
    payment_instruction_html,
)


def _sample_instruction():
    return {
        "organisation_name": "Center for Marine and Offshore Technology Development",
        "document_title": "Approved Payment Instruction",
        "request_id": 145,
        "request_reference": "UF-20260729-093353-145",
        "department_project": "Administration",
        "purchase_summary": "Payment for the purchase of 1 × ZTecko Clock in. Purpose: A new clock in device for staff use.",
        "approved_vendor_payee": "ZTecko LTD.",
        "account_name": "ZTecko LTD.",
        "bank_name": "FIDELITY",
        "account_number": "5430908878",
        "currency": "NGN",
        "approved_amount": 49500,
        "payment_method": "Bank Transfer",
        "approver": "Procurement Manager",
        "approval_date": "2026-07-29T11:34:22+00:00",
        "date_generated": "2026-07-29T11:40:34+00:00",
        "generated_by_user_id": 5,
        "generated_by_role": "Finance",
        "payment_id": None,
        "payment_reference": "UF-20260729-093353-145",
        "logo_path": None,
    }


def test_purchase_summary_uses_line_items_and_business_purpose():
    summary = _build_purchase_summary(
        [{"item_name": "ZTecko Clock in", "quantity": 1}],
        "We would need a new clock in device for staffs",
    )
    assert summary == "Payment for the purchase of 1 clock-in device for staff use."


def test_payment_instruction_html_is_concise_and_structured():
    html = payment_instruction_html(_sample_instruction(), "Finance Manager")
    assert "Payment Summary" in html
    assert "Vendor Account Details" in html
    assert "Approved Amount" in html
    assert "NGN 49,500.00" in html
    assert "Account Number" in html
    assert "5430908878" in html
    assert "Approved By:" in html
    assert "2026-07-29 11:34:22" in html

    # These operational fields remain in the underlying dictionary but are
    # intentionally omitted from the concise payment slip.
    for hidden_label in (
        "Purchase order",
        "Finance verification",
        "Generated by",
        "Approval status",
        "Payment / reconciliation reference",
        "Transfer type",
    ):
        assert hidden_label not in html


def test_payment_instruction_pdf_remains_valid():
    pdf = generate_payment_instruction_pdf(_sample_instruction(), "Finance Manager")
    assert pdf.startswith(b"%PDF")
    assert len(pdf) > 1500
