-- ProcureFlow PostgreSQL baseline generated from the production SQLite schema.
-- Apply with scripts/migrate_sqlite_to_postgres.py or core.postgres_schema.
BEGIN;
SET TIME ZONE 'UTC';
CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, checksum TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS "activity_logs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT,
    "role" TEXT,
    "action" TEXT NOT NULL,
    "entity_type" TEXT,
    "entity_id" BIGINT,
    "public_summary" TEXT,
    "private_details" TEXT,
    "visibility_scope" TEXT DEFAULT 'role',
    "related_user_id" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "advance_expenses" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "advance_id" BIGINT NOT NULL,
    "spent_date" DATE NOT NULL,
    "description" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "amount" NUMERIC(18, 4) NOT NULL,
    "receipt_path" TEXT,
    "receipt_hash" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "annual_budgets" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "budget_year" BIGINT NOT NULL,
    "department_project" TEXT DEFAULT 'General',
    "category" TEXT DEFAULT 'All',
    "annual_amount" NUMERIC(18, 4) NOT NULL DEFAULT 0,
    "distribution_json" JSONB,
    "notes" TEXT,
    "created_by" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    UNIQUE ("budget_year", "department_project", "category")
);

CREATE TABLE IF NOT EXISTS "approval_delegations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "primary_role" TEXT NOT NULL,
    "delegate_role" TEXT NOT NULL,
    "enabled" BOOLEAN DEFAULT FALSE,
    "start_date" DATE,
    "end_date" DATE,
    "reason" TEXT,
    "created_by" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    "source_availability_id" BIGINT,
    "source_reason" TEXT,
    "activated_by_admin_id" BIGINT,
    "activation_note" TEXT,
    "primary_user_id" BIGINT,
    "delegate_user_id" BIGINT
);

CREATE TABLE IF NOT EXISTS "approval_history" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "entity_type" TEXT NOT NULL,
    "entity_id" BIGINT NOT NULL,
    "action" TEXT NOT NULL,
    "status_before" TEXT,
    "status_after" TEXT,
    "reason" TEXT,
    "user_id" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "approved_by_user_id" BIGINT,
    "approved_by_role" TEXT,
    "approval_mode" TEXT DEFAULT 'Normal Approval Mode',
    "delegation_reason" TEXT,
    "original_approver_role" TEXT,
    "note" TEXT
);

CREATE TABLE IF NOT EXISTS "approval_rules" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "category" TEXT,
    "threshold_amount" NUMERIC(18, 4) DEFAULT 0,
    "approver_role" TEXT DEFAULT 'Approver',
    "requires_sourcing" BOOLEAN DEFAULT FALSE,
    "requires_finance" BOOLEAN DEFAULT TRUE,
    "is_active" BOOLEAN DEFAULT TRUE,
    "created_at" TIMESTAMPTZ NOT NULL,
    "primary_approver_role" TEXT DEFAULT 'Approver',
    "backup_approver_role" TEXT,
    "pm_fallback_enabled" BOOLEAN DEFAULT FALSE,
    "finance_required" BOOLEAN DEFAULT TRUE,
    "sourcing_required" BOOLEAN DEFAULT FALSE,
    "approval_timeout_hours" BIGINT DEFAULT 48,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "attachments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "entity_type" TEXT NOT NULL,
    "entity_id" BIGINT,
    "file_name" TEXT NOT NULL,
    "file_path" TEXT NOT NULL,
    "file_hash" TEXT,
    "mime_type" TEXT,
    "uploaded_by" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "audit_chain_verifications" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "verified_at" TIMESTAMPTZ NOT NULL,
    "checked_count" BIGINT NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL,
    "invalid_event_ids_json" JSONB,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "audit_events" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "occurred_at" TIMESTAMPTZ NOT NULL,
    "correlation_id" TEXT NOT NULL,
    "entity_type" TEXT NOT NULL,
    "entity_id" TEXT,
    "entity_reference" TEXT,
    "parent_entity_type" TEXT,
    "parent_entity_id" BIGINT,
    "actor_user_id" BIGINT,
    "actor_username" TEXT,
    "actor_role" TEXT,
    "action" TEXT NOT NULL,
    "outcome" TEXT NOT NULL DEFAULT 'Success',
    "severity" TEXT NOT NULL DEFAULT 'Normal',
    "source" TEXT NOT NULL DEFAULT 'application',
    "ip_address" TEXT,
    "user_agent" TEXT,
    "session_id_hash" TEXT,
    "before_values_redacted_json" JSONB,
    "after_values_redacted_json" JSONB,
    "metadata_redacted_json" JSONB,
    "reason_or_comment" TEXT,
    "canonical_payload_json" JSONB NOT NULL,
    "previous_event_hash" TEXT NOT NULL,
    "record_hash" TEXT NOT NULL,
    "record_signature" TEXT NOT NULL,
    "signature_key_version" TEXT NOT NULL DEFAULT 'v1',
    "created_at" TIMESTAMPTZ NOT NULL,
    UNIQUE ("record_hash")
);

CREATE TABLE IF NOT EXISTS "audit_logs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "action" TEXT NOT NULL,
    "entity_type" TEXT NOT NULL,
    "entity_id" TEXT,
    "user_id" BIGINT,
    "role" TEXT,
    "details" TEXT,
    "before_values" JSONB,
    "after_values" JSONB,
    "created_at" TIMESTAMPTZ NOT NULL,
    "event_date" TEXT,
    "event_time" TEXT,
    "session_id" BIGINT,
    "amount" NUMERIC(18, 4),
    "department" TEXT,
    "project" TEXT,
    "notes" TEXT
);

CREATE TABLE IF NOT EXISTS "budget_adjustments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "budget_type" TEXT NOT NULL,
    "budget_id" BIGINT,
    "budget_month" TEXT,
    "budget_year" BIGINT,
    "department_project" TEXT,
    "category" TEXT,
    "adjustment_amount" NUMERIC(18, 4) NOT NULL DEFAULT 0,
    "reason" TEXT,
    "adjusted_by" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "budget_history" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "budget_type" TEXT NOT NULL,
    "budget_id" BIGINT,
    "action" TEXT NOT NULL,
    "before_values" JSONB,
    "after_values" JSONB,
    "note" TEXT,
    "changed_by" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "budgets" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "budget_month" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "department_project" TEXT DEFAULT 'General',
    "limit_amount" NUMERIC(18, 4) NOT NULL,
    "override_required" BOOLEAN DEFAULT FALSE,
    "created_at" TIMESTAMPTZ NOT NULL,
    UNIQUE ("budget_month", "category", "department_project")
);

CREATE TABLE IF NOT EXISTS "cash_advances" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "advance_no" TEXT NOT NULL,
    "date_collected" DATE NOT NULL,
    "employee_name" TEXT NOT NULL,
    "amount_collected" NUMERIC(18, 4) NOT NULL,
    "purpose" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "created_by" BIGINT NOT NULL,
    "approved_by" BIGINT,
    "approved_at" TIMESTAMPTZ,
    "due_date" DATE,
    "created_at" TIMESTAMPTZ NOT NULL,
    UNIQUE ("advance_no")
);

CREATE TABLE IF NOT EXISTS "categories" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "category_type" TEXT DEFAULT 'Procurement',
    "status" TEXT DEFAULT 'Active',
    "created_at" TIMESTAMPTZ NOT NULL,
    UNIQUE ("name")
);

CREATE TABLE IF NOT EXISTS "collaboration_messages" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "thread_id" BIGINT NOT NULL,
    "sender_user_id" BIGINT NOT NULL,
    "message_text" TEXT,
    "attachment_path" TEXT,
    "is_private" BIGINT DEFAULT 1,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "collaboration_threads" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "entity_type" TEXT NOT NULL,
    "entity_id" BIGINT NOT NULL,
    "facility_manager_user_id" BIGINT,
    "procurement_manager_user_id" BIGINT,
    "visibility_scope" TEXT DEFAULT 'FM_PM_ADMIN',
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    UNIQUE ("entity_type", "entity_id", "facility_manager_user_id", "procurement_manager_user_id")
);

CREATE TABLE IF NOT EXISTS "comments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "entity_type" TEXT NOT NULL,
    "entity_id" BIGINT NOT NULL,
    "comment_text" TEXT NOT NULL,
    "is_internal" BIGINT DEFAULT 0,
    "user_id" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "custom_dropdown_values" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "field_name" TEXT NOT NULL,
    "custom_value" TEXT NOT NULL,
    "created_by" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL,
    UNIQUE ("field_name", "custom_value")
);

CREATE TABLE IF NOT EXISTS "departments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "status" TEXT DEFAULT 'Active',
    "created_at" TIMESTAMPTZ NOT NULL,
    UNIQUE ("name")
);

CREATE TABLE IF NOT EXISTS "document_extraction_logs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "source_zip_name" TEXT,
    "original_path" TEXT,
    "action" TEXT,
    "status" TEXT,
    "message" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "document_ocr_attempts" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "document_type" TEXT NOT NULL,
    "entity_id" BIGINT,
    "file_hash" TEXT,
    "engine" TEXT,
    "success" BOOLEAN DEFAULT FALSE,
    "extracted_chars" BIGINT DEFAULT 0,
    "error_message" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "expenses" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "expense_no" TEXT NOT NULL,
    "expense_date" DATE NOT NULL,
    "category" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "vendor_id" BIGINT,
    "amount" NUMERIC(18, 4) NOT NULL,
    "payment_method" TEXT NOT NULL,
    "project_department" TEXT,
    "status" TEXT NOT NULL,
    "receipt_path" TEXT,
    "receipt_hash" TEXT,
    "receipt_no" TEXT,
    "invoice_no" TEXT,
    "tax_amount" NUMERIC(18, 4) DEFAULT 0,
    "linked_po_id" BIGINT,
    "invoice_match_status" TEXT DEFAULT 'Not Matched',
    "duplicate_warning" BOOLEAN DEFAULT FALSE,
    "requested_by" BIGINT NOT NULL,
    "approved_by" BIGINT,
    "approved_at" TIMESTAMPTZ,
    "rejection_reason" TEXT,
    "ocr_text" TEXT,
    "ocr_json" JSONB,
    "notes" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "document_kind" TEXT DEFAULT 'Expense',
    "receipt_id" BIGINT,
    UNIQUE ("expense_no")
);

CREATE TABLE IF NOT EXISTS "facility_manager_links" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "facility_manager_user_id" BIGINT NOT NULL,
    "procurement_manager_user_id" BIGINT NOT NULL,
    "is_active" BIGINT DEFAULT 1,
    "created_by" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    UNIQUE ("facility_manager_user_id", "procurement_manager_user_id")
);

CREATE TABLE IF NOT EXISTS "gateway_pass_approvals" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "gateway_pass_id" BIGINT NOT NULL,
    "approver_user_id" BIGINT,
    "approver_role" TEXT,
    "decision" TEXT NOT NULL,
    "note" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "gateway_pass_events" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "gateway_pass_id" BIGINT NOT NULL,
    "event" TEXT NOT NULL,
    "status" TEXT,
    "note" TEXT,
    "user_id" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "gateway_pass_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "gateway_pass_id" BIGINT NOT NULL,
    "item_description" TEXT NOT NULL,
    "item_category" TEXT,
    "quantity" NUMERIC(18, 4) NOT NULL,
    "unit_of_measure" TEXT NOT NULL,
    "quality_condition" TEXT NOT NULL,
    "estimated_value" NUMERIC(18, 4),
    "serial_number" TEXT,
    "asset_tag" TEXT,
    "fragility_status" TEXT NOT NULL,
    "handling_instruction" TEXT,
    "remarks" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "colour" TEXT
);

CREATE TABLE IF NOT EXISTS "gateway_passes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "pass_number" TEXT NOT NULL,
    "facility_manager_user_id" BIGINT NOT NULL,
    "department_id" BIGINT,
    "department" TEXT,
    "movement_type" TEXT NOT NULL,
    "purpose" TEXT NOT NULL,
    "origin_location" TEXT,
    "destination" TEXT,
    "expected_movement_date" DATE,
    "expected_return_date" DATE,
    "vehicle_number" TEXT,
    "driver_name" TEXT,
    "driver_phone" TEXT,
    "receiver_name" TEXT,
    "receiver_organization" TEXT,
    "security_checkpoint" TEXT,
    "security_officer_name" TEXT,
    "gate_verification_time" TEXT,
    "exit_entry_confirmation" TEXT,
    "security_signature" TEXT,
    "actual_return_date" DATE,
    "status" TEXT DEFAULT 'Draft',
    "submitted_at" TIMESTAMPTZ,
    "approved_at" TIMESTAMPTZ,
    "approved_by_user_id" BIGINT,
    "approved_by_role" TEXT,
    "approval_note" TEXT,
    "rejected_at" TIMESTAMPTZ,
    "rejected_by_user_id" BIGINT,
    "rejection_reason" TEXT,
    "generated_at" TIMESTAMPTZ,
    "downloaded_at" TIMESTAMPTZ,
    "generated_file_path" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    "logistics_status" TEXT DEFAULT 'Not Coordinated',
    "logistics_movement_date" TEXT,
    "logistics_delivery_reference" TEXT,
    "logistics_waybill_number" TEXT,
    "logistics_note" TEXT,
    "logistics_updated_by" BIGINT,
    "logistics_updated_at" TIMESTAMPTZ,
    "next_role" TEXT,
    "reviewed_by_user_id" BIGINT,
    "reviewed_at" TIMESTAMPTZ,
    "procurement_review_note" TEXT,
    "completed_at" TIMESTAMPTZ,
    UNIQUE ("pass_number")
);

CREATE TABLE IF NOT EXISTS "imported_legacy_documents" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "source_zip_name" TEXT,
    "original_path" TEXT,
    "file_name" TEXT,
    "file_path" TEXT,
    "file_hash" TEXT,
    "document_type" TEXT,
    "department_project" TEXT,
    "title" TEXT,
    "likely_date" DATE,
    "likely_vendor" TEXT,
    "total_amount" NUMERIC(18, 4) DEFAULT 0,
    "import_status" TEXT DEFAULT 'Imported - Needs Review',
    "confidence" NUMERIC(18, 4) DEFAULT 0,
    "extracted_text" TEXT,
    "parsed_json" JSONB,
    "linked_request_id" BIGINT,
    "duplicate_warning" BOOLEAN DEFAULT FALSE,
    "imported_by" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    "assigned_procurement_manager_id" BIGINT,
    "facility_manager_user_id" BIGINT,
    UNIQUE ("original_path")
);

CREATE TABLE IF NOT EXISTS "income_entries" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "entry_no" TEXT,
    "entry_date" DATE NOT NULL,
    "month_key" TEXT NOT NULL,
    "year" BIGINT NOT NULL,
    "month" BIGINT NOT NULL,
    "department" TEXT DEFAULT 'General',
    "project" TEXT DEFAULT 'General',
    "source" TEXT DEFAULT 'Opening income / budget allocation',
    "entry_type" TEXT DEFAULT 'Opening income / budget allocation',
    "amount" NUMERIC(18, 4) NOT NULL DEFAULT 0,
    "notes" TEXT,
    "status" TEXT DEFAULT 'Active',
    "created_by" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    UNIQUE ("entry_no")
);

CREATE TABLE IF NOT EXISTS "invoice_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "invoice_id" BIGINT NOT NULL,
    "item_description" TEXT NOT NULL,
    "quantity" NUMERIC(18, 4) DEFAULT 1,
    "unit_price" NUMERIC(18, 4) DEFAULT 0,
    "tax_amount" NUMERIC(18, 4) DEFAULT 0,
    "total" NUMERIC(18, 4) DEFAULT 0,
    "category" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "invoices" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "invoice_no" TEXT,
    "receipt_no" TEXT,
    "po_id" BIGINT,
    "vendor_id" BIGINT,
    "invoice_date" DATE,
    "amount" NUMERIC(18, 4) DEFAULT 0,
    "tax_amount" NUMERIC(18, 4) DEFAULT 0,
    "total_amount" NUMERIC(18, 4) DEFAULT 0,
    "file_path" TEXT,
    "file_hash" TEXT,
    "ocr_text" TEXT,
    "ocr_json" JSONB,
    "match_status" TEXT DEFAULT 'Needs Review',
    "mismatch_reasons" TEXT,
    "status" TEXT DEFAULT 'Uploaded',
    "uploaded_by" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "invoice_type" TEXT DEFAULT 'Supplier Invoice',
    "document_stage" TEXT DEFAULT 'Invoice',
    "supplier_invoice_no" TEXT,
    "due_date" DATE,
    "payment_terms" TEXT,
    "billing_address" TEXT,
    "shipping_address" TEXT,
    "subtotal" NUMERIC(18, 4) DEFAULT 0,
    "discount_amount" NUMERIC(18, 4) DEFAULT 0,
    "balance_due" NUMERIC(18, 4) DEFAULT 0,
    "linked_request_id" BIGINT,
    "approval_status" TEXT DEFAULT 'Needs Review',
    "detected_document_type" TEXT,
    "ocr_detected_date" TEXT,
    "interface_mode" TEXT
);

CREATE TABLE IF NOT EXISTS "logistics_documents" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "related_entity_type" TEXT NOT NULL,
    "related_entity_id" BIGINT NOT NULL,
    "po_id" BIGINT,
    "gateway_pass_id" BIGINT,
    "document_type" TEXT NOT NULL,
    "file_name" TEXT,
    "file_path" TEXT NOT NULL,
    "notes" TEXT,
    "uploaded_by" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "logistics_exceptions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "exception_no" TEXT NOT NULL,
    "po_id" BIGINT NOT NULL,
    "request_id" BIGINT,
    "exception_type" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "payment_impact" BOOLEAN DEFAULT FALSE,
    "status" TEXT DEFAULT 'Open',
    "raised_by" BIGINT,
    "resolved_by" BIGINT,
    "resolution_note" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    UNIQUE ("exception_no")
);

CREATE TABLE IF NOT EXISTS "notification_outbox" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "notification_id" BIGINT,
    "channel" TEXT NOT NULL,
    "target_user_id" BIGINT,
    "target_role" TEXT,
    "status" TEXT DEFAULT 'Queued',
    "attempts" BIGINT DEFAULT 0,
    "error_message" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "sent_at" TIMESTAMPTZ,
    "recipient_email" TEXT,
    "subject" TEXT,
    "body" TEXT,
    "last_failure_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "notification_preferences" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "in_app_enabled" BOOLEAN DEFAULT TRUE,
    "browser_push_enabled" BOOLEAN DEFAULT FALSE,
    "email_enabled" BOOLEAN DEFAULT FALSE,
    "important_only" BOOLEAN DEFAULT TRUE,
    "approval_notifications" BOOLEAN DEFAULT TRUE,
    "gateway_pass_notifications" BOOLEAN DEFAULT TRUE,
    "finance_notifications" BOOLEAN DEFAULT TRUE,
    "delegation_notifications" BOOLEAN DEFAULT TRUE,
    "browser_permission_status" TEXT DEFAULT 'not_requested',
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    UNIQUE ("user_id")
);

CREATE TABLE IF NOT EXISTS "notification_settings" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role" TEXT NOT NULL,
    "email_enabled" BOOLEAN DEFAULT FALSE,
    "in_app_enabled" BOOLEAN DEFAULT TRUE,
    "created_at" TIMESTAMPTZ NOT NULL,
    UNIQUE ("role")
);

CREATE TABLE IF NOT EXISTS "notifications" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT,
    "role" TEXT,
    "title" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "entity_type" TEXT,
    "entity_id" BIGINT,
    "is_read" BOOLEAN DEFAULT FALSE,
    "created_at" TIMESTAMPTZ NOT NULL,
    "popup_shown" BOOLEAN DEFAULT FALSE,
    "importance" TEXT DEFAULT 'Normal',
    "delivery_channel" TEXT DEFAULT 'in_app',
    "push_sent" BOOLEAN DEFAULT FALSE,
    "email_sent" BOOLEAN DEFAULT FALSE,
    "action_url" TEXT,
    "action_label" TEXT,
    "expires_at" TIMESTAMPTZ,
    "section_target" TEXT,
    "attention_counted" BOOLEAN DEFAULT TRUE,
    UNIQUE ("user_id", "role", "title", "entity_type", "entity_id", "message")
);

CREATE TABLE IF NOT EXISTS "parsed_document_line_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "imported_doc_id" BIGINT NOT NULL,
    "row_number" BIGINT,
    "item_name" TEXT,
    "description" TEXT,
    "quantity" NUMERIC(18, 4) DEFAULT 0,
    "unit_price" NUMERIC(18, 4) DEFAULT 0,
    "total_price" NUMERIC(18, 4) DEFAULT 0,
    "category" TEXT,
    "status_of_purchase" TEXT,
    "raw_json" JSONB,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "password_history" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "payment_payee_detail_versions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "payee_detail_id" BIGINT NOT NULL,
    "version_no" BIGINT NOT NULL,
    "action" TEXT NOT NULL,
    "values_redacted_json" JSONB NOT NULL,
    "changed_by_user_id" BIGINT,
    "reason" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL,
    UNIQUE ("payee_detail_id", "version_no")
);

CREATE TABLE IF NOT EXISTS "payment_payee_details" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "purchase_request_id" BIGINT,
    "purchase_order_id" BIGINT,
    "vendor_id" BIGINT,
    "payee_type" TEXT,
    "payee_name_encrypted" TEXT,
    "payee_name_masked" TEXT,
    "account_name_encrypted" TEXT,
    "account_name_masked" TEXT,
    "bank_name_encrypted" TEXT,
    "bank_name_masked" TEXT,
    "account_number_encrypted" TEXT,
    "account_number_last4" TEXT,
    "account_number_fingerprint" TEXT,
    "currency" TEXT DEFAULT 'NGN',
    "payment_reference_encrypted" TEXT,
    "contact_email_encrypted" TEXT,
    "contact_phone_encrypted" TEXT,
    "recipient_known" BOOLEAN NOT NULL DEFAULT FALSE,
    "payment_readiness_status" TEXT DEFAULT 'Pending Payee Details',
    "verification_status" TEXT DEFAULT 'Pending',
    "confirmed_by_user_id" BIGINT,
    "confirmed_at" TIMESTAMPTZ,
    "verified_by_user_id" BIGINT,
    "verified_at" TIMESTAMPTZ,
    "rejected_reason_encrypted" TEXT,
    "source_attachment_path" TEXT,
    "source_attachment_hash" TEXT,
    "created_by_user_id" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_by_user_id" BIGINT,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "payments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "payment_no" TEXT NOT NULL,
    "invoice_id" BIGINT,
    "po_id" BIGINT,
    "vendor_id" BIGINT,
    "amount" NUMERIC(18, 4) NOT NULL,
    "payment_method" TEXT,
    "payment_date" DATE,
    "status" TEXT DEFAULT 'Pending Approval',
    "approved_by" BIGINT,
    "paid_by" BIGINT,
    "notes" TEXT,
    "created_by" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    "proof_path" TEXT,
    "finance_note" TEXT,
    "approved_by_role" TEXT,
    "approval_mode" TEXT DEFAULT 'Normal Approval Mode',
    "receipt_id" BIGINT,
    "request_id" BIGINT,
    "next_role" TEXT,
    "submitted_for_verification_at" TIMESTAMPTZ,
    UNIQUE ("payment_no")
);

CREATE TABLE IF NOT EXISTS "permissions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL,
    UNIQUE ("name")
);

CREATE TABLE IF NOT EXISTS "purchase_order_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "po_id" BIGINT NOT NULL,
    "item_name" TEXT NOT NULL,
    "description" TEXT,
    "quantity" NUMERIC(18, 4) NOT NULL,
    "unit_price" NUMERIC(18, 4) NOT NULL,
    "total" NUMERIC(18, 4) NOT NULL,
    "category" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "purchase_orders" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "po_no" TEXT NOT NULL,
    "request_id" BIGINT,
    "vendor_id" BIGINT,
    "po_date" DATE NOT NULL,
    "expected_delivery_date" DATE,
    "status" TEXT DEFAULT 'Draft',
    "total_amount" NUMERIC(18, 4) DEFAULT 0,
    "approved_by" BIGINT,
    "sent_to_vendor_date" DATE,
    "payment_status" TEXT DEFAULT 'Unpaid',
    "receiving_status" TEXT DEFAULT 'Pending Receipt',
    "attachments_json" JSONB,
    "created_by" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    "approved_by_role" TEXT,
    "approval_mode" TEXT DEFAULT 'Normal Approval Mode',
    "next_role" TEXT,
    "released_to_logistics_at" TIMESTAMPTZ,
    "released_to_logistics_by" BIGINT,
    "logistics_status" TEXT DEFAULT 'Not Released',
    "vendor_delivery_contact" TEXT,
    "delivery_address" TEXT,
    "driver_name" TEXT,
    "driver_phone" TEXT,
    "vehicle_number" TEXT,
    "waybill_number" TEXT,
    "delivery_instructions" TEXT,
    "actual_delivery_date" DATE,
    "delivery_updated_at" TIMESTAMPTZ,
    "delivery_updated_by" BIGINT,
    "delivery_exception_status" TEXT DEFAULT 'None',
    UNIQUE ("po_no")
);

CREATE TABLE IF NOT EXISTS "purchase_request_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "request_id" BIGINT NOT NULL,
    "item_name" TEXT NOT NULL,
    "description" TEXT,
    "quantity" NUMERIC(18, 4) NOT NULL,
    "unit_price" NUMERIC(18, 4) NOT NULL,
    "total" NUMERIC(18, 4) NOT NULL,
    "category" TEXT,
    "suggested_vendor" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "purchase_requests" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "request_no" TEXT NOT NULL,
    "requested_by" BIGINT NOT NULL,
    "department_project" TEXT,
    "request_date" DATE NOT NULL,
    "required_date" DATE,
    "category" TEXT,
    "justification" TEXT,
    "priority" TEXT DEFAULT 'Normal',
    "estimated_amount" NUMERIC(18, 4) DEFAULT 0,
    "vendor_preference" TEXT,
    "status" TEXT DEFAULT 'Draft',
    "source_type" TEXT DEFAULT 'Manual',
    "imported_doc_id" BIGINT,
    "import_confidence" DOUBLE PRECISION DEFAULT 0,
    "attachments_json" JSONB,
    "notes" TEXT,
    "approval_history_json" JSONB,
    "linked_sourcing_task_id" BIGINT,
    "linked_po_id" BIGINT,
    "linked_receiving_slip_id" BIGINT,
    "linked_expense_id" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    "payment_status" TEXT DEFAULT 'Not Ready',
    "facility_manager_user_id" BIGINT,
    "assigned_procurement_manager_id" BIGINT,
    "official_request_id" BIGINT,
    "converted_from_draft_id" BIGINT,
    "approval_due_at" TIMESTAMPTZ,
    "delegated_approval_allowed" BOOLEAN DEFAULT FALSE,
    "finance_note" TEXT,
    "next_role" TEXT,
    "request_type" TEXT DEFAULT 'Procurement',
    "submitted_at" TIMESTAMPTZ,
    "approved_at" TIMESTAMPTZ,
    "approved_by_user_id" BIGINT,
    "approved_by_role" TEXT,
    "approval_mode" TEXT DEFAULT 'Normal Approval Mode',
    "paid_at" TIMESTAMPTZ,
    "receipt_uploaded_at" TIMESTAMPTZ,
    "completed_at" TIMESTAMPTZ,
    "generated_at" TIMESTAMPTZ,
    UNIQUE ("request_no")
);

CREATE TABLE IF NOT EXISTS "push_subscriptions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "endpoint" TEXT,
    "p256dh_key" TEXT,
    "auth_key" TEXT,
    "user_agent" TEXT,
    "is_active" BOOLEAN DEFAULT TRUE,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    "last_success_at" TIMESTAMPTZ,
    "last_failure_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "quote_comparisons" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sourcing_task_id" BIGINT NOT NULL,
    "lowest_price_vendor" TEXT,
    "fastest_delivery_vendor" TEXT,
    "best_rated_vendor" TEXT,
    "recommended_vendor" TEXT,
    "scoring_json" JSONB,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "receipt_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "receipt_id" BIGINT NOT NULL,
    "item_description" TEXT NOT NULL,
    "quantity" NUMERIC(18, 4) DEFAULT 1,
    "unit_price" NUMERIC(18, 4) DEFAULT 0,
    "total" NUMERIC(18, 4) DEFAULT 0,
    "category" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "receipt_records" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "receipt_no" TEXT,
    "receipt_type" TEXT DEFAULT 'Payment Receipt',
    "payment_method" TEXT NOT NULL,
    "payment_date" DATE NOT NULL,
    "vendor_id" BIGINT,
    "payer_name" TEXT,
    "payee_name" TEXT,
    "amount" NUMERIC(18, 4) NOT NULL DEFAULT 0,
    "tax_amount" NUMERIC(18, 4) DEFAULT 0,
    "currency" TEXT DEFAULT 'NGN',
    "purpose" TEXT,
    "department_project" TEXT,
    "linked_invoice_id" BIGINT,
    "linked_payment_id" BIGINT,
    "linked_po_id" BIGINT,
    "cash_received_by" TEXT,
    "cash_collected_from" TEXT,
    "cash_denominations" JSONB,
    "bank_name" TEXT,
    "account_name" TEXT,
    "account_number" TEXT,
    "transfer_reference" TEXT,
    "sender_bank" TEXT,
    "receiver_bank" TEXT,
    "card_type" TEXT,
    "masked_card_number" TEXT,
    "card_auth_code" TEXT,
    "pos_terminal_id" TEXT,
    "pos_merchant_id" TEXT,
    "pos_rrn" TEXT,
    "cheque_number" TEXT,
    "cheque_bank" TEXT,
    "cheque_due_date" DATE,
    "mobile_wallet_provider" TEXT,
    "mobile_transaction_id" TEXT,
    "status" TEXT DEFAULT 'Recorded',
    "file_path" TEXT,
    "file_hash" TEXT,
    "ocr_text" TEXT,
    "ocr_json" JSONB,
    "duplicate_warning" BOOLEAN DEFAULT FALSE,
    "notes" TEXT,
    "uploaded_by" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    "detected_document_type" TEXT,
    "ocr_detected_date" TEXT,
    "interface_mode" TEXT
);

CREATE TABLE IF NOT EXISTS "receiving_slip_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "slip_id" BIGINT NOT NULL,
    "po_item_id" BIGINT,
    "item_name" TEXT NOT NULL,
    "quantity_ordered" DOUBLE PRECISION NOT NULL,
    "quantity_received" DOUBLE PRECISION NOT NULL,
    "item_condition" TEXT DEFAULT 'Good',
    "discrepancy_notes" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "receiving_slips" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "slip_no" TEXT NOT NULL,
    "po_id" BIGINT NOT NULL,
    "vendor_id" BIGINT,
    "received_by" BIGINT,
    "date_received" DATE NOT NULL,
    "delivery_note_no" TEXT,
    "discrepancy_notes" TEXT,
    "attachment_path" TEXT,
    "status" TEXT DEFAULT 'Pending Receipt',
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    "logistics_officer_id" BIGINT,
    "proof_of_delivery_path" TEXT,
    UNIQUE ("slip_no")
);

CREATE TABLE IF NOT EXISTS "role_permissions" (
    "role_name" TEXT NOT NULL,
    "permission_name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    UNIQUE ("role_name", "permission_name")
);

CREATE TABLE IF NOT EXISTS "roles" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL,
    UNIQUE ("name")
);

CREATE TABLE IF NOT EXISTS "section_attention_reads" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "role" TEXT NOT NULL,
    "section" TEXT NOT NULL,
    "last_seen_at" TIMESTAMPTZ NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    UNIQUE ("user_id", "role", "section")
);

CREATE TABLE IF NOT EXISTS "sourcing_tasks" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sourcing_no" TEXT NOT NULL,
    "request_id" BIGINT NOT NULL,
    "required_item_service" TEXT,
    "assigned_to" BIGINT,
    "status" TEXT DEFAULT 'Open',
    "recommended_vendor_id" BIGINT,
    "reason_for_recommendation" TEXT,
    "approval_status" TEXT DEFAULT 'Pending',
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    UNIQUE ("sourcing_no")
);

CREATE TABLE IF NOT EXISTS "user_availability" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "role" TEXT NOT NULL,
    "status" TEXT DEFAULT 'Away Requested',
    "away_start_date" DATE NOT NULL,
    "away_end_date" DATE NOT NULL,
    "reason" TEXT NOT NULL,
    "handover_note" TEXT,
    "recommended_delegate_role" TEXT,
    "recommended_delegate_user_id" BIGINT,
    "urgency" TEXT DEFAULT 'Normal',
    "admin_review_status" TEXT DEFAULT 'Pending Review',
    "reviewed_by_admin_id" BIGINT,
    "reviewed_at" TIMESTAMPTZ,
    "linked_delegation_id" BIGINT,
    "admin_note" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "user_sessions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "session_token" TEXT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "login_at" TIMESTAMPTZ NOT NULL,
    "logout_at" TIMESTAMPTZ,
    "last_seen_at" TIMESTAMPTZ,
    "status" TEXT DEFAULT 'Active',
    "user_agent" TEXT,
    "ip_address" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    "remember_me" BIGINT DEFAULT 0,
    "expires_at" TIMESTAMPTZ,
    UNIQUE ("session_token")
);

CREATE TABLE IF NOT EXISTS "users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" TEXT NOT NULL,
    "full_name" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "must_change_password" BOOLEAN DEFAULT FALSE,
    "is_active" BOOLEAN DEFAULT TRUE,
    "last_login_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL,
    "email" TEXT,
    "account_locked" BOOLEAN DEFAULT FALSE,
    "failed_login_count" BIGINT DEFAULT 0,
    "updated_at" TIMESTAMPTZ,
    UNIQUE ("username")
);

CREATE TABLE IF NOT EXISTS "vendor_documents" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "vendor_id" BIGINT,
    "title" TEXT,
    "document_type" TEXT,
    "file_path" TEXT,
    "file_hash" TEXT,
    "notes" TEXT,
    "uploaded_by" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "vendor_quotes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sourcing_task_id" BIGINT NOT NULL,
    "vendor_id" BIGINT,
    "vendor_name" TEXT,
    "quoted_amount" NUMERIC(18, 4) NOT NULL,
    "delivery_time_days" DOUBLE PRECISION DEFAULT 0,
    "payment_terms" TEXT,
    "warranty" TEXT,
    "vendor_rating" BIGINT DEFAULT 3,
    "notes" TEXT,
    "attachment_path" TEXT,
    "is_recommended" BOOLEAN DEFAULT FALSE,
    "score" NUMERIC(18, 4) DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "vendors" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "category" TEXT,
    "phone" TEXT,
    "email" TEXT,
    "address" TEXT,
    "bank_name" TEXT,
    "account_no" TEXT,
    "tax_id" TEXT,
    "rating" BIGINT DEFAULT 3,
    "completed_orders" BIGINT DEFAULT 0,
    "total_spend" NUMERIC(18, 4) DEFAULT 0,
    "average_delivery_time" DOUBLE PRECISION DEFAULT 0,
    "rejection_count" BIGINT DEFAULT 0,
    "last_purchase_date" DATE,
    "status" TEXT DEFAULT 'Active',
    "documents_json" JSONB,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    UNIQUE ("name")
);

CREATE TABLE IF NOT EXISTS "workflow_events" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "entity_type" TEXT NOT NULL,
    "entity_id" BIGINT NOT NULL,
    "event" TEXT NOT NULL,
    "status" TEXT,
    "note" TEXT,
    "user_id" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_activity_logs_user_role ON activity_logs(user_id, role, related_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_approval_delegations_enabled ON approval_delegations(enabled, primary_role, delegate_role, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_audit_department_project ON audit_logs(department, project, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_events_action ON audit_events(action, outcome, severity, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_actor ON audit_events(actor_user_id, actor_role, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_correlation ON audit_events(correlation_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_entity ON audit_events(entity_type, entity_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_time ON audit_events(occurred_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action_date ON audit_logs(action, event_date, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_gateway_pass_items_pass_fragile ON gateway_pass_items(gateway_pass_id, fragility_status);
CREATE INDEX IF NOT EXISTS idx_gateway_pass_logistics_status ON gateway_passes(logistics_status, expected_movement_date, updated_at);
CREATE INDEX IF NOT EXISTS idx_gateway_passes_fm_status ON gateway_passes(facility_manager_user_id, status, updated_at);
CREATE INDEX IF NOT EXISTS idx_gateway_passes_status_dates ON gateway_passes(status, created_at, submitted_at, approved_at);
CREATE INDEX IF NOT EXISTS idx_gp_next_role_status ON gateway_passes(next_role, status, updated_at);
CREATE INDEX IF NOT EXISTS idx_income_month_dept_project ON income_entries(year, month, department, project, status);
CREATE INDEX IF NOT EXISTS idx_invoice_items_invoice ON invoice_items(invoice_id);
CREATE INDEX IF NOT EXISTS idx_invoices_po_vendor ON invoices(po_id, vendor_id, total_amount);
CREATE INDEX IF NOT EXISTS idx_invoices_status_date ON invoices(status, invoice_date, created_at);
CREATE INDEX IF NOT EXISTS idx_logistics_documents_entity ON logistics_documents(related_entity_type, related_entity_id, created_at);
CREATE INDEX IF NOT EXISTS idx_logistics_exceptions_po_status ON logistics_exceptions(po_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_notification_outbox_status_channel ON notification_outbox(channel, status, target_user_id, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_notifications_dedupe_recent ON notifications(user_id, role, title, entity_type, entity_id, message);
CREATE INDEX IF NOT EXISTS idx_notifications_role_read_popup ON notifications(role, is_read, popup_shown, created_at);
CREATE INDEX IF NOT EXISTS idx_notifications_section_attention ON notifications(is_read, section_target, created_at);
CREATE INDEX IF NOT EXISTS idx_notifications_section_role_attention ON notifications(section_target, role, user_id, is_read, created_at);
CREATE INDEX IF NOT EXISTS idx_notifications_section_unread ON notifications(user_id, role, section_target, is_read, created_at);
CREATE INDEX IF NOT EXISTS idx_notifications_user_read_popup ON notifications(user_id, is_read, popup_shown, created_at);
CREATE INDEX IF NOT EXISTS idx_ocr_attempts_doc ON document_ocr_attempts(document_type, entity_id, created_at);
CREATE INDEX IF NOT EXISTS idx_password_history_user_created ON password_history(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pay_next_role_status ON payments(next_role, status, updated_at);
CREATE INDEX IF NOT EXISTS idx_payee_fingerprint ON payment_payee_details(account_number_fingerprint);
CREATE INDEX IF NOT EXISTS idx_payee_request ON payment_payee_details(purchase_request_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_payee_versions ON payment_payee_detail_versions(payee_detail_id, version_no DESC);
CREATE INDEX IF NOT EXISTS idx_payments_request_receipt ON payments(request_id, receipt_id, status);
CREATE INDEX IF NOT EXISTS idx_payments_status_method ON payments(status, payment_method, created_at);
CREATE INDEX IF NOT EXISTS idx_po_logistics_queue ON purchase_orders(next_role, status, logistics_status, expected_delivery_date);
CREATE INDEX IF NOT EXISTS idx_pr_department_project ON purchase_requests(department_project, category);
CREATE INDEX IF NOT EXISTS idx_pr_next_role_status ON purchase_requests(next_role, status, updated_at);
CREATE INDEX IF NOT EXISTS idx_pr_request_type ON purchase_requests(request_type, status);
CREATE INDEX IF NOT EXISTS idx_pr_status_created ON purchase_requests(status, created_at);
CREATE INDEX IF NOT EXISTS idx_purchase_requests_fm_status ON purchase_requests(facility_manager_user_id, status, updated_at);
CREATE INDEX IF NOT EXISTS idx_purchase_requests_pm_status ON purchase_requests(assigned_procurement_manager_id, status, updated_at);
CREATE INDEX IF NOT EXISTS idx_purchase_requests_requested_by ON purchase_requests(requested_by, status, updated_at);
CREATE INDEX IF NOT EXISTS idx_purchase_requests_status_updated ON purchase_requests(status, updated_at);
CREATE INDEX IF NOT EXISTS idx_receipt_items_receipt ON receipt_items(receipt_id);
CREATE INDEX IF NOT EXISTS idx_receipts_method_status ON receipt_records(payment_method, status, payment_date);
CREATE INDEX IF NOT EXISTS idx_receipts_vendor_amount ON receipt_records(vendor_id, amount, payment_date);
CREATE INDEX IF NOT EXISTS idx_section_attention_reads_user_section ON section_attention_reads(user_id, role, section, last_seen_at);
CREATE INDEX IF NOT EXISTS idx_user_availability_status ON user_availability(user_id, status, admin_review_status, away_start_date, away_end_date);
CREATE INDEX IF NOT EXISTS idx_user_sessions_token ON user_sessions(session_token);
CREATE INDEX IF NOT EXISTS idx_user_sessions_user_status ON user_sessions(user_id, status, login_at, logout_at);

COMMIT;
