-- ProcureFlow E2E workflow and presentation-support schema.
BEGIN;
SET TIME ZONE 'UTC';

ALTER TABLE vendor_quotes ADD COLUMN IF NOT EXISTS request_id BIGINT;
ALTER TABLE vendor_quotes ADD COLUMN IF NOT EXISTS currency TEXT NOT NULL DEFAULT 'NGN';
ALTER TABLE vendor_quotes ADD COLUMN IF NOT EXISTS quote_date DATE;
ALTER TABLE vendor_quotes ADD COLUMN IF NOT EXISTS supply_description TEXT;
ALTER TABLE vendor_quotes ADD COLUMN IF NOT EXISTS quote_document_path TEXT;
ALTER TABLE vendor_quotes ADD COLUMN IF NOT EXISTS quote_document_hash TEXT;
ALTER TABLE vendor_quotes ADD COLUMN IF NOT EXISTS quotation_total NUMERIC(18,4);
ALTER TABLE vendor_quotes ADD COLUMN IF NOT EXISTS is_selected BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE vendor_quotes ADD COLUMN IF NOT EXISTS selected_at TIMESTAMPTZ;
ALTER TABLE vendor_quotes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS vendor_quote_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_quote_id BIGINT NOT NULL,
    request_item_id BIGINT,
    item_description TEXT NOT NULL,
    quantity NUMERIC(18,4) NOT NULL DEFAULT 0,
    unit_price NUMERIC(18,4) NOT NULL DEFAULT 0,
    line_total NUMERIC(18,4) NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'NGN',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    UNIQUE (vendor_quote_id, request_item_id, item_description)
);

ALTER TABLE purchase_requests ADD COLUMN IF NOT EXISTS selected_vendor_id BIGINT;
ALTER TABLE purchase_requests ADD COLUMN IF NOT EXISTS selected_vendor_quote_id BIGINT;
ALTER TABLE purchase_requests ADD COLUMN IF NOT EXISTS selected_payee_detail_id BIGINT;
ALTER TABLE purchase_requests ADD COLUMN IF NOT EXISTS approval_rescinded_at TIMESTAMPTZ;
ALTER TABLE purchase_requests ADD COLUMN IF NOT EXISTS approval_rescinded_reason TEXT;
ALTER TABLE purchase_requests ADD COLUMN IF NOT EXISTS completed_by_user_id BIGINT;
ALTER TABLE purchase_requests ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ;
ALTER TABLE purchase_requests ADD COLUMN IF NOT EXISTS archived_by_user_id BIGINT;

CREATE TABLE IF NOT EXISTS approval_rescissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type TEXT NOT NULL,
    entity_id BIGINT NOT NULL,
    approval_history_id BIGINT,
    original_approver_user_id BIGINT,
    original_approver_role TEXT,
    original_approval_at TIMESTAMPTZ,
    rescinded_by_user_id BIGINT NOT NULL,
    rescinded_by_role TEXT NOT NULL,
    reason TEXT NOT NULL,
    previous_status TEXT NOT NULL,
    new_status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (entity_type, entity_id, approval_history_id)
);

ALTER TABLE payment_payee_details ADD COLUMN IF NOT EXISTS approval_history_id BIGINT;
ALTER TABLE payment_payee_details ADD COLUMN IF NOT EXISTS is_current BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE payment_payee_details ADD COLUMN IF NOT EXISTS replaced_at TIMESTAMPTZ;
ALTER TABLE payment_payee_details ADD COLUMN IF NOT EXISTS replaced_by_user_id BIGINT;
ALTER TABLE payment_payee_details ADD COLUMN IF NOT EXISTS replacement_reason TEXT;

ALTER TABLE payments ADD COLUMN IF NOT EXISTS transfer_type TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payee_detail_id BIGINT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS approval_history_id BIGINT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS proof_of_payment_receipt_id BIGINT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS vendor_receipt_id BIGINT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS currency TEXT NOT NULL DEFAULT 'NGN';
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_reference TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS verification_status TEXT DEFAULT 'Pending';
ALTER TABLE payments ADD COLUMN IF NOT EXISTS instruction_generated_at TIMESTAMPTZ;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS instruction_generated_by BIGINT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS notification_dedupe_key TEXT;

ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS document_category TEXT;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS request_id BIGINT;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS payment_id BIGINT;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS original_file_name TEXT;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS mime_type TEXT;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS file_size_bytes BIGINT;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS file_checksum TEXT;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS ocr_status TEXT NOT NULL DEFAULT 'Pending';
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS ocr_confidence NUMERIC(7,4);
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS extracted_vendor_payee TEXT;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS extracted_account_name TEXT;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS extracted_bank_name TEXT;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS extracted_transaction_reference TEXT;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS extracted_document_number TEXT;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS extracted_payment_time TEXT;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS extracted_amount NUMERIC(18,4);
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS extracted_currency TEXT;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS extracted_payer TEXT;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS extracted_payee TEXT;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS extracted_description TEXT;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS extracted_tax_amount NUMERIC(18,4);
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS extracted_total_amount NUMERIC(18,4);
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS original_ocr_json JSONB;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS corrected_ocr_json JSONB;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS discrepancy_status TEXT DEFAULT 'Not Checked';
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS discrepancy_details TEXT;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS corrected_by_user_id BIGINT;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS corrected_at TIMESTAMPTZ;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS processing_started_at TIMESTAMPTZ;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS processing_completed_at TIMESTAMPTZ;
ALTER TABLE receipt_records ADD COLUMN IF NOT EXISTS retry_count BIGINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS receipt_document_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id BIGINT NOT NULL,
    version_no BIGINT NOT NULL,
    action TEXT NOT NULL,
    file_path TEXT NOT NULL,
    original_file_name TEXT,
    mime_type TEXT,
    file_size_bytes BIGINT,
    file_checksum TEXT NOT NULL,
    uploaded_by_user_id BIGINT NOT NULL,
    reason TEXT,
    ocr_status TEXT,
    original_ocr_json JSONB,
    corrected_ocr_json JSONB,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (receipt_id, version_no)
);

ALTER TABLE notifications ADD COLUMN IF NOT EXISTS dedupe_key TEXT;
ALTER TABLE notification_outbox ADD COLUMN IF NOT EXISTS dedupe_key TEXT;
ALTER TABLE notification_outbox ADD COLUMN IF NOT EXISTS attempt_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE notification_outbox ADD COLUMN IF NOT EXISTS last_attempt_at TIMESTAMPTZ;

CREATE UNIQUE INDEX IF NOT EXISTS idx_notifications_dedupe_key ON notifications(dedupe_key) WHERE dedupe_key IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_notification_outbox_dedupe_key ON notification_outbox(dedupe_key) WHERE dedupe_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_vendor_quotes_request_vendor ON vendor_quotes(request_id, vendor_id, quoted_amount);
CREATE INDEX IF NOT EXISTS idx_vendor_quote_items_quote ON vendor_quote_items(vendor_quote_id, request_item_id);
CREATE INDEX IF NOT EXISTS idx_rescissions_entity ON approval_rescissions(entity_type, entity_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payments_request_status ON payments(request_id, status, payment_date);
CREATE INDEX IF NOT EXISTS idx_payments_payee ON payments(payee_detail_id, request_id, status);
CREATE INDEX IF NOT EXISTS idx_payments_receipt_categories ON payments(proof_of_payment_receipt_id, vendor_receipt_id);
CREATE INDEX IF NOT EXISTS idx_receipts_request_payment ON receipt_records(request_id, payment_id, document_category, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_receipts_ocr_status ON receipt_records(ocr_status, status, discrepancy_status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_receipt_versions_receipt ON receipt_document_versions(receipt_id, version_no DESC);
CREATE INDEX IF NOT EXISTS idx_purchase_requests_archive ON purchase_requests(status, archived_at, completed_at);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='ck_payments_transfer_type') THEN
        ALTER TABLE payments ADD CONSTRAINT ck_payments_transfer_type
        CHECK (transfer_type IS NULL OR transfer_type IN ('Internet Bank Transfer','Physical Bank Transfer'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='ck_receipt_document_category') THEN
        ALTER TABLE receipt_records ADD CONSTRAINT ck_receipt_document_category
        CHECK (document_category IS NULL OR document_category IN ('Proof of Payment','Vendor Receipt'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='ck_receipt_ocr_status') THEN
        ALTER TABLE receipt_records ADD CONSTRAINT ck_receipt_ocr_status
        CHECK (ocr_status IN ('Pending','Processing','Extracted','Review Required','Verified','Failed'));
    END IF;
END $$;

COMMIT;
