-- Vendor governance, classification, nominations, profiles and real graduation vendor seed.
-- Additive and backwards-compatible with existing ProcureFlow vendor records.

ALTER TABLE vendors
  ADD COLUMN IF NOT EXISTS contact_person TEXT,
  ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'Procurement Direct',
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS created_by_user_id BIGINT,
  ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS archived_by_user_id BIGINT;

CREATE TABLE IF NOT EXISTS vendor_operational_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'Active',
  created_by_user_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS vendor_service_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'Active',
  created_by_user_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS vendor_category_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id BIGINT NOT NULL,
  operational_category_id BIGINT NOT NULL,
  service_category_id BIGINT NOT NULL,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  created_by_user_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (vendor_id, operational_category_id, service_category_id)
);

CREATE TABLE IF NOT EXISTS vendor_nominations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submitted_by_user_id BIGINT NOT NULL,
  vendor_name TEXT NOT NULL,
  contact_person TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  operational_category_id BIGINT NOT NULL,
  service_category_id BIGINT NOT NULL,
  reason TEXT NOT NULL,
  prior_experience TEXT,
  status TEXT NOT NULL DEFAULT 'Pending Procurement Review',
  procurement_note TEXT,
  reviewed_by_user_id BIGINT,
  reviewed_at TIMESTAMPTZ,
  approved_vendor_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_vendor_category_links_vendor
  ON vendor_category_links (vendor_id, is_primary, created_at);
CREATE INDEX IF NOT EXISTS idx_vendor_category_links_operation
  ON vendor_category_links (operational_category_id, service_category_id);
CREATE INDEX IF NOT EXISTS idx_vendor_nominations_status
  ON vendor_nominations (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vendor_nominations_submitter
  ON vendor_nominations (submitted_by_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vendors_status_name
  ON vendors (status, name);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_vendor_created_by_user') THEN
    ALTER TABLE vendors ADD CONSTRAINT fk_vendor_created_by_user
      FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_vendor_archived_by_user') THEN
    ALTER TABLE vendors ADD CONSTRAINT fk_vendor_archived_by_user
      FOREIGN KEY (archived_by_user_id) REFERENCES users(id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_vendor_operation_created_by') THEN
    ALTER TABLE vendor_operational_categories ADD CONSTRAINT fk_vendor_operation_created_by
      FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_vendor_service_created_by') THEN
    ALTER TABLE vendor_service_categories ADD CONSTRAINT fk_vendor_service_created_by
      FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_vendor_category_link_vendor') THEN
    ALTER TABLE vendor_category_links ADD CONSTRAINT fk_vendor_category_link_vendor
      FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE CASCADE NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_vendor_category_link_operation') THEN
    ALTER TABLE vendor_category_links ADD CONSTRAINT fk_vendor_category_link_operation
      FOREIGN KEY (operational_category_id) REFERENCES vendor_operational_categories(id) ON DELETE RESTRICT NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_vendor_category_link_service') THEN
    ALTER TABLE vendor_category_links ADD CONSTRAINT fk_vendor_category_link_service
      FOREIGN KEY (service_category_id) REFERENCES vendor_service_categories(id) ON DELETE RESTRICT NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_vendor_category_link_created_by') THEN
    ALTER TABLE vendor_category_links ADD CONSTRAINT fk_vendor_category_link_created_by
      FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_vendor_nomination_submitter') THEN
    ALTER TABLE vendor_nominations ADD CONSTRAINT fk_vendor_nomination_submitter
      FOREIGN KEY (submitted_by_user_id) REFERENCES users(id) ON DELETE RESTRICT NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_vendor_nomination_operation') THEN
    ALTER TABLE vendor_nominations ADD CONSTRAINT fk_vendor_nomination_operation
      FOREIGN KEY (operational_category_id) REFERENCES vendor_operational_categories(id) ON DELETE RESTRICT NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_vendor_nomination_service') THEN
    ALTER TABLE vendor_nominations ADD CONSTRAINT fk_vendor_nomination_service
      FOREIGN KEY (service_category_id) REFERENCES vendor_service_categories(id) ON DELETE RESTRICT NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_vendor_nomination_reviewer') THEN
    ALTER TABLE vendor_nominations ADD CONSTRAINT fk_vendor_nomination_reviewer
      FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_vendor_nomination_approved_vendor') THEN
    ALTER TABLE vendor_nominations ADD CONSTRAINT fk_vendor_nomination_approved_vendor
      FOREIGN KEY (approved_vendor_id) REFERENCES vendors(id) ON DELETE SET NULL NOT VALID;
  END IF;
END $$;

INSERT INTO vendor_operational_categories (name, description)
VALUES
  ('Graduation', 'Graduation ceremonies and related programme close-out activities'),
  ('Training Programme', 'Training delivery and programme support activities'),
  ('Conference / Workshop', 'Conferences, workshops, seminars and professional events'),
  ('Facility Operations', 'Facility, premises and utility operations'),
  ('ICT Operations', 'Information technology, software, connectivity and digital operations'),
  ('Office Administration', 'Office administration and general support'),
  ('Marine / Technical Training', 'Marine, offshore and technical training operations'),
  ('Maintenance', 'Repairs, servicing and maintenance activities'),
  ('Events / Protocol', 'Events, protocol, hospitality and official functions')
ON CONFLICT (name) DO NOTHING;

INSERT INTO vendor_service_categories (name, description)
VALUES
  ('Polos / Apparel', 'Branded polos, clothing, uniforms and apparel'),
  ('Branding / Graphics', 'Branding, graphics, design and visual communication'),
  ('Decoration', 'Venue decoration and event styling'),
  ('Food / Catering', 'Food, refreshments and catering services'),
  ('Fuel / Energy', 'Diesel, fuel, energy and related supplies'),
  ('Office Supplies', 'Stationery and general office supplies'),
  ('ICT / Software', 'ICT equipment, software and technology services'),
  ('Repairs / Maintenance', 'Repairs, maintenance and technical servicing'),
  ('Training Materials', 'Course materials, learning aids and participant packs'),
  ('Printing / Publishing', 'Printing, publishing and document production'),
  ('Transport / Logistics', 'Transportation, movement and logistics services'),
  ('Equipment / Tools', 'Equipment, tools and technical supplies'),
  ('Professional Services', 'Specialist and professional services'),
  ('Other', 'Other approved vendor services')
ON CONFLICT (name) DO NOTHING;

-- Existing production vendor rows were confirmed by the business owner to be placeholders.
-- Preserve any historical transaction links by archiving rather than deleting them automatically.
UPDATE vendors
SET status='Archived',
    source='Legacy Placeholder',
    archived_at=COALESCE(archived_at,NOW()),
    notes=COALESCE(notes,'Legacy placeholder vendor retained only for historical test/audit references.'),
    updated_at=NOW()
WHERE name IN (
  'ABC Diesel Supply','Prime Office Mart','FixRight Maintenance','Sandra Attitude',
  'ZLTX PRO','Zee Supplies','AB Supplies LTD','XYZ Repairs'
);

-- Seed the supplied real Graduation vendors without duplicating them if the migration is replayed.
INSERT INTO vendors (name, contact_person, phone, email, address, category, rating, completed_orders, total_spend, rejection_count, status, source, notes, created_at, updated_at)
SELECT 'Kingsword Global','Kingsley','09119476329',NULL,NULL,'Polos / Apparel',3,0,0,0,'Active','Graduation Vendor List','Supplied as a real vendor used for Graduation.',NOW(),NOW()
WHERE NOT EXISTS (SELECT 1 FROM vendors WHERE LOWER(TRIM(name))=LOWER('Kingsword Global'));

INSERT INTO vendors (name, contact_person, phone, email, address, category, rating, completed_orders, total_spend, rejection_count, status, source, notes, created_at, updated_at)
SELECT 'Joechimez Digital Services','Ifeanyi Joel','07067492078',NULL,NULL,'Branding / Graphics',3,0,0,0,'Active','Graduation Vendor List','Supplied as a real vendor used for Graduation.',NOW(),NOW()
WHERE NOT EXISTS (SELECT 1 FROM vendors WHERE LOWER(TRIM(name))=LOWER('Joechimez Digital Services'));

INSERT INTO vendors (name, contact_person, phone, email, address, category, rating, completed_orders, total_spend, rejection_count, status, source, notes, created_at, updated_at)
SELECT 'Nkem Decorations',NULL,'07035329248',NULL,NULL,'Decoration',3,0,0,0,'Active','Graduation Vendor List','Supplied as a real vendor used for Graduation.',NOW(),NOW()
WHERE NOT EXISTS (SELECT 1 FROM vendors WHERE LOWER(TRIM(name))=LOWER('Nkem Decorations'));

INSERT INTO vendors (name, contact_person, phone, email, address, category, rating, completed_orders, total_spend, rejection_count, status, source, notes, created_at, updated_at)
SELECT 'De Jay’s &Vee Services',NULL,'07036543252/09126869296','Rennerpatience@Gmail.Com','N0 82 Ogbum-Nu-Abali Road, Port Harcourt','Food / Catering',3,0,0,0,'Active','Graduation Vendor List','Supplied as a real vendor used for Graduation.',NOW(),NOW()
WHERE NOT EXISTS (SELECT 1 FROM vendors WHERE LOWER(TRIM(name))=LOWER('De Jay’s &Vee Services'));

INSERT INTO vendor_category_links (vendor_id, operational_category_id, service_category_id, is_primary)
SELECT v.id, oc.id, sc.id, TRUE FROM vendors v
JOIN vendor_operational_categories oc ON oc.name='Graduation'
JOIN vendor_service_categories sc ON sc.name='Polos / Apparel'
WHERE LOWER(TRIM(v.name))=LOWER('Kingsword Global')
ON CONFLICT (vendor_id, operational_category_id, service_category_id) DO UPDATE SET is_primary=TRUE;

INSERT INTO vendor_category_links (vendor_id, operational_category_id, service_category_id, is_primary)
SELECT v.id, oc.id, sc.id, TRUE FROM vendors v
JOIN vendor_operational_categories oc ON oc.name='Graduation'
JOIN vendor_service_categories sc ON sc.name='Branding / Graphics'
WHERE LOWER(TRIM(v.name))=LOWER('Joechimez Digital Services')
ON CONFLICT (vendor_id, operational_category_id, service_category_id) DO UPDATE SET is_primary=TRUE;

INSERT INTO vendor_category_links (vendor_id, operational_category_id, service_category_id, is_primary)
SELECT v.id, oc.id, sc.id, TRUE FROM vendors v
JOIN vendor_operational_categories oc ON oc.name='Graduation'
JOIN vendor_service_categories sc ON sc.name='Decoration'
WHERE LOWER(TRIM(v.name))=LOWER('Nkem Decorations')
ON CONFLICT (vendor_id, operational_category_id, service_category_id) DO UPDATE SET is_primary=TRUE;

INSERT INTO vendor_category_links (vendor_id, operational_category_id, service_category_id, is_primary)
SELECT v.id, oc.id, sc.id, TRUE FROM vendors v
JOIN vendor_operational_categories oc ON oc.name='Graduation'
JOIN vendor_service_categories sc ON sc.name='Food / Catering'
WHERE LOWER(TRIM(v.name))=LOWER('De Jay’s &Vee Services')
ON CONFLICT (vendor_id, operational_category_id, service_category_id) DO UPDATE SET is_primary=TRUE;
