-- Return Pass lifecycle linked to approved Gateway Passes.
-- Additive and backwards-compatible with the live Gateway Pass workflow.

ALTER TABLE gateway_passes
  ADD COLUMN IF NOT EXISTS return_status TEXT DEFAULT 'Not Started',
  ADD COLUMN IF NOT EXISTS last_return_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS return_completed_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS return_passes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_pass_number TEXT NOT NULL UNIQUE,
  gateway_pass_id BIGINT NOT NULL,
  facility_manager_user_id BIGINT NOT NULL,
  department TEXT,
  purpose TEXT,
  return_origin TEXT,
  receiving_location TEXT,
  actual_return_date DATE,
  vehicle_number TEXT,
  driver_name TEXT,
  driver_phone TEXT,
  security_checkpoint TEXT,
  security_officer_name TEXT,
  gate_verification_time TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'Draft',
  next_role TEXT DEFAULT 'facility_manager',
  submitted_at TIMESTAMPTZ,
  reviewed_at TIMESTAMPTZ,
  reviewed_by_user_id BIGINT,
  approved_at TIMESTAMPTZ,
  approved_by_user_id BIGINT,
  approved_by_role TEXT,
  approval_note TEXT,
  rejected_at TIMESTAMPTZ,
  rejected_by_user_id BIGINT,
  rejection_reason TEXT,
  generated_at TIMESTAMPTZ,
  downloaded_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS return_pass_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_pass_id BIGINT NOT NULL,
  gateway_pass_item_id BIGINT NOT NULL,
  quantity_outbound NUMERIC(18,4) NOT NULL,
  quantity_previously_returned NUMERIC(18,4) NOT NULL DEFAULT 0,
  quantity_returned NUMERIC(18,4) NOT NULL DEFAULT 0,
  condition_on_return TEXT NOT NULL DEFAULT 'Good',
  discrepancy_type TEXT,
  discrepancy_notes TEXT,
  remarks TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  UNIQUE (return_pass_id, gateway_pass_item_id)
);

CREATE TABLE IF NOT EXISTS return_pass_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_pass_id BIGINT NOT NULL,
  event TEXT NOT NULL,
  status TEXT,
  note TEXT,
  user_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_return_pass_gateway ON return_passes (gateway_pass_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_return_pass_status ON return_passes (status, next_role, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_return_pass_facility ON return_passes (facility_manager_user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_return_pass_items_gateway_item ON return_pass_items (gateway_pass_item_id, return_pass_id);
CREATE INDEX IF NOT EXISTS idx_gateway_return_status ON gateway_passes (return_status, expected_return_date, updated_at DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_return_pass_gateway') THEN
    ALTER TABLE return_passes ADD CONSTRAINT fk_return_pass_gateway
      FOREIGN KEY (gateway_pass_id) REFERENCES gateway_passes(id) ON DELETE RESTRICT NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_return_pass_facility') THEN
    ALTER TABLE return_passes ADD CONSTRAINT fk_return_pass_facility
      FOREIGN KEY (facility_manager_user_id) REFERENCES users(id) ON DELETE RESTRICT NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_return_pass_reviewed_by') THEN
    ALTER TABLE return_passes ADD CONSTRAINT fk_return_pass_reviewed_by
      FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_return_pass_approved_by') THEN
    ALTER TABLE return_passes ADD CONSTRAINT fk_return_pass_approved_by
      FOREIGN KEY (approved_by_user_id) REFERENCES users(id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_return_pass_rejected_by') THEN
    ALTER TABLE return_passes ADD CONSTRAINT fk_return_pass_rejected_by
      FOREIGN KEY (rejected_by_user_id) REFERENCES users(id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_return_pass_item_return') THEN
    ALTER TABLE return_pass_items ADD CONSTRAINT fk_return_pass_item_return
      FOREIGN KEY (return_pass_id) REFERENCES return_passes(id) ON DELETE CASCADE NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_return_pass_item_gateway_item') THEN
    ALTER TABLE return_pass_items ADD CONSTRAINT fk_return_pass_item_gateway_item
      FOREIGN KEY (gateway_pass_item_id) REFERENCES gateway_pass_items(id) ON DELETE RESTRICT NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_return_pass_event_return') THEN
    ALTER TABLE return_pass_events ADD CONSTRAINT fk_return_pass_event_return
      FOREIGN KEY (return_pass_id) REFERENCES return_passes(id) ON DELETE CASCADE NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_return_pass_event_user') THEN
    ALTER TABLE return_pass_events ADD CONSTRAINT fk_return_pass_event_user
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL NOT VALID;
  END IF;
END $$;
