#!/usr/bin/env python3
"""Generate the checked-in PostgreSQL baseline from the live SQLite schema.

This is a maintainer utility. Production deployments apply the generated SQL;
they do not generate schema dynamically at application startup.
"""
from __future__ import annotations

import argparse
import re
import sqlite3
from pathlib import Path

BOOLEAN_COLUMNS = {
    "users": {"must_change_password", "is_active", "account_locked"},
    "approval_rules": {"requires_sourcing", "requires_finance", "is_active", "pm_fallback_enabled", "finance_required", "sourcing_required"},
    "approval_delegations": {"enabled"},
    "budgets": {"override_required"},
    "purchase_requests": {"delegated_approval_allowed"},
    "vendor_quotes": {"is_recommended"},
    "notifications": {"is_read", "popup_shown", "push_sent", "email_sent", "attention_counted"},
    "notification_settings": {"email_enabled", "in_app_enabled"},
    "notification_preferences": {"in_app_enabled", "browser_push_enabled", "email_enabled", "important_only", "approval_notifications", "gateway_pass_notifications", "finance_notifications", "delegation_notifications"},
    "push_subscriptions": {"is_active"},
    "expenses": {"duplicate_warning"},
    "receipt_records": {"duplicate_warning"},
    "imported_legacy_documents": {"duplicate_warning"},
    "document_ocr_attempts": {"success"},
    "payment_payee_details": {"recipient_known"},
    "logistics_exceptions": {"payment_impact"},
}

JSON_COLUMNS = {
    "distribution_json", "attachments_json", "approval_history_json", "documents_json",
    "ocr_json", "parsed_json", "raw_json", "scoring_json", "invalid_event_ids_json",
    "before_values", "after_values", "before_values_redacted_json", "after_values_redacted_json",
    "metadata_redacted_json", "canonical_payload_json", "values_redacted_json", "cash_denominations",
}

MONEY_HINTS = (
    "amount", "price", "total", "spend", "value", "limit", "tax", "subtotal",
    "discount", "balance", "budget", "collected",
)
DATE_EXACT = {
    "request_date", "required_date", "po_date", "expected_delivery_date", "sent_to_vendor_date",
    "date_received", "expense_date", "invoice_date", "due_date", "payment_date", "spent_date",
    "date_collected", "last_purchase_date", "away_start_date", "away_end_date", "start_date", "end_date",
    "expected_movement_date", "expected_return_date", "actual_return_date", "actual_delivery_date",
    "cheque_due_date", "entry_date", "likely_date",
}


def quote_ident(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def pg_type(table: str, name: str, sqlite_type: str, is_pk: bool) -> str:
    upper = (sqlite_type or "TEXT").upper()
    if is_pk and upper == "INTEGER":
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY"
    if name in BOOLEAN_COLUMNS.get(table, set()):
        return "BOOLEAN"
    if upper == "INTEGER":
        return "BIGINT"
    if upper in {"REAL", "FLOAT", "DOUBLE"}:
        if any(hint in name.lower() for hint in MONEY_HINTS) or name.lower() in {"quantity", "score", "confidence"}:
            return "NUMERIC(18, 4)"
        return "DOUBLE PRECISION"
    if upper in {"BLOB", "BYTEA"}:
        return "BYTEA"
    lname = name.lower()
    if lname in JSON_COLUMNS or lname.endswith("_json"):
        return "JSONB"
    if lname.endswith("_at") or lname in {"occurred_at", "login_at", "logout_at", "last_seen_at", "expires_at"}:
        return "TIMESTAMPTZ"
    if lname in DATE_EXACT:
        return "DATE"
    return "TEXT"


def pg_default(default: str | None, target_type: str) -> str | None:
    if default is None:
        return None
    raw = str(default).strip()
    if target_type == "BOOLEAN":
        if raw.strip("()'").lower() in {"0", "false"}:
            return "FALSE"
        if raw.strip("()'").lower() in {"1", "true"}:
            return "TRUE"
    if target_type == "JSONB":
        if raw.startswith("'") and raw.endswith("'"):
            return raw + "::jsonb"
        return f"'{raw}'::jsonb"
    raw = re.sub(r"datetime\s*\(\s*'now'\s*\)", "CURRENT_TIMESTAMP", raw, flags=re.I)
    return raw


def generate(sqlite_path: Path) -> str:
    con = sqlite3.connect(sqlite_path)
    con.row_factory = sqlite3.Row
    tables = [r[0] for r in con.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")]
    out = [
        "-- ProcureFlow PostgreSQL baseline generated from the production SQLite schema.",
        "-- Apply with scripts/migrate_sqlite_to_postgres.py or core.postgres_schema.",
        "BEGIN;",
        "SET TIME ZONE 'UTC';",
        "CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, checksum TEXT NOT NULL);",
        "",
    ]
    for table in tables:
        cols = list(con.execute(f"PRAGMA table_info({quote_ident(table)})"))
        pk_cols = [r["name"] for r in sorted(cols, key=lambda r: r["pk"]) if r["pk"]]
        lines = []
        for col in cols:
            name = str(col["name"])
            is_pk = bool(col["pk"])
            typ = pg_type(table, name, str(col["type"]), is_pk and len(pk_cols) == 1)
            pieces = [quote_ident(name), typ]
            if is_pk and len(pk_cols) == 1:
                pieces.append("PRIMARY KEY")
            if col["notnull"]:
                pieces.append("NOT NULL")
            default = pg_default(col["dflt_value"], typ)
            if default is not None:
                pieces.append("DEFAULT " + default)
            lines.append("    " + " ".join(pieces))
        if len(pk_cols) > 1:
            lines.append("    PRIMARY KEY (" + ", ".join(quote_ident(c) for c in pk_cols) + ")")
        # Preserve all SQLite unique constraints/indexes as table constraints.
        unique_sets: list[tuple[str, ...]] = []
        for idx in con.execute(f"PRAGMA index_list({quote_ident(table)})"):
            if not idx["unique"] or str(idx["origin"]) == "pk":
                continue
            names = tuple(r["name"] for r in con.execute(f"PRAGMA index_info({quote_ident(idx['name'])})") if r["name"] is not None)
            if names and names not in unique_sets:
                unique_sets.append(names)
        for names in unique_sets:
            lines.append("    UNIQUE (" + ", ".join(quote_ident(c) for c in names) + ")")
        out.append(f"CREATE TABLE IF NOT EXISTS {quote_ident(table)} (\n" + ",\n".join(lines) + "\n);")
        out.append("")

    # Preserve explicitly named indexes. Automatic indexes are represented by
    # the UNIQUE/PRIMARY KEY constraints emitted above.
    for row in con.execute("SELECT name, sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL ORDER BY name"):
        sql = str(row["sql"]).strip().rstrip(";")
        sql = re.sub(r"^CREATE\s+UNIQUE\s+INDEX", "CREATE UNIQUE INDEX IF NOT EXISTS", sql, flags=re.I)
        sql = re.sub(r"^CREATE\s+INDEX", "CREATE INDEX IF NOT EXISTS", sql, flags=re.I)
        out.append(sql + ";")
    out.extend(["", "COMMIT;", ""])
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sqlite", default="data/procureflow_workspace.db")
    parser.add_argument("--output", default="migrations/postgresql/001_initial_schema.sql")
    args = parser.parse_args()
    content = generate(Path(args.sqlite))
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
