import { createHash, randomUUID } from "node:crypto";
import { db } from "@/lib/db";
import type { CurrentUser } from "@/lib/auth";
import { appendAuditEvent } from "./audit";

const MAX_EMBEDDED_FILE_BYTES = 3_000_000;

function assertRole(user: CurrentUser, allowed: string[]) {
  if (!allowed.includes(user.role)) throw new Error(`This action is not available to ${user.role}.`);
}
function clean(value: unknown, max = 4000) { return String(value ?? "").trim().replace(/\s+/g, " ").slice(0, max); }
function positiveId(value: unknown, label = "record") { const n=Number(value); if(!Number.isInteger(n)||n<=0) throw new Error(`Choose a valid ${label}.`); return n; }
function money(value: unknown, label = "amount") { const n=Number(value); if(!Number.isFinite(n)||n<0) throw new Error(`Enter a valid ${label}.`); return n; }
function reason(value: unknown) { const v=clean(value,2000); if(v.length<4) throw new Error("Enter a meaningful reason or note."); return v; }
function ref(prefix:string){return `${prefix}-${new Date().toISOString().replace(/[-:TZ.]/g,"").slice(0,17)}-${randomUUID().slice(0,8).toUpperCase()}`;}
function maskAccount(value:string){const d=value.replace(/\D/g,""); return d ? `••••${d.slice(-4)}` : "";}

function filePayload(input:any) {
  if (!input?.base64) return null;
  const fileName = clean(input.fileName, 180) || "document";
  const mimeType = clean(input.mimeType, 120) || "application/octet-stream";
  const normalized = String(input.base64).replace(/^data:[^;]+;base64,/, "").replace(/\s+/g, "");
  const bytes = Buffer.from(normalized, "base64");
  if (!bytes.length) throw new Error("The uploaded file is empty.");
  if (bytes.length > MAX_EMBEDDED_FILE_BYTES) throw new Error("This file is too large for the current secure Neon document store. Keep individual files below 3 MB.");
  const checksum = createHash("sha256").update(bytes).digest("hex");
  return { fileName, mimeType, bytes: bytes.length, checksum, locator: `data:${mimeType};base64,${bytes.toString("base64")}` };
}

async function evidence(tx:any, user:CurrentUser, input:{action:string;entityType:string;entityId?:number|null;entityReference?:string|null;before?:Record<string,unknown>;after?:Record<string,unknown>;note?:string;relatedUserId?:number|null;severity?:string}){
  const now=new Date().toISOString(); const note=clean(input.note,2000); const before=input.before||{}; const after=input.after||{};
  await tx`INSERT INTO activity_logs (user_id,role,action,entity_type,entity_id,public_summary,private_details,visibility_scope,related_user_id,created_at) VALUES (${user.id},${user.role},${input.action},${input.entityType},${input.entityId??null},${`${input.action}${input.entityReference?` — ${input.entityReference}`:""}`},${note||null},'workflow',${input.relatedUserId??null},${now})`;
  await tx`INSERT INTO audit_logs (action,entity_type,entity_id,user_id,role,details,before_values,after_values,created_at,event_date,event_time,notes) VALUES (${input.action.toUpperCase().replace(/[^A-Z0-9]+/g,"_")},${input.entityType},${input.entityId==null?null:String(input.entityId)},${user.id},${user.role},${note||input.action},${tx.json(before)},${tx.json(after)},${now},${now.slice(0,10)},${now.slice(11,19)},${note||null})`;
  await appendAuditEvent(tx,{action:input.action,entityType:input.entityType,entityId:input.entityId??null,entityReference:input.entityReference??null,actorUserId:user.id,actorUsername:user.username,actorRole:user.role,beforeValues:before,afterValues:after,metadata:{source:"full-parity-port"},reasonOrComment:note||input.action,severity:input.severity||"Normal",source:"nextjs"});
}

async function workflow(tx:any,user:CurrentUser,entityType:string,entityId:number,event:string,status:string|null,note:string){await tx`INSERT INTO workflow_events (entity_type,entity_id,event,status,note,user_id,created_at) VALUES (${entityType},${entityId},${event},${status},${note||null},${user.id},NOW())`;}
async function notifyRole(tx:any,role:string,title:string,message:string,entityType:string,entityId:number|null,section:string,importance="Normal"){await tx`INSERT INTO notifications (user_id,role,title,message,entity_type,entity_id,is_read,popup_shown,importance,delivery_channel,push_sent,email_sent,action_label,section_target,created_at) VALUES (NULL,${role},${title},${message},${entityType},${entityId},FALSE,FALSE,${importance},'in_app',FALSE,FALSE,'Open',${section},NOW())`;}
async function notifyUser(tx:any,userId:number,title:string,message:string,entityType:string,entityId:number|null,section:string,importance="Normal"){await tx`INSERT INTO notifications (user_id,role,title,message,entity_type,entity_id,is_read,popup_shown,importance,delivery_channel,push_sent,email_sent,action_label,section_target,created_at) VALUES (${userId},NULL,${title},${message},${entityType},${entityId},FALSE,FALSE,${importance},'in_app',FALSE,FALSE,'Open',${section},NOW())`;}

export async function runParityAction(user:CurrentUser, action:string, payload:any){
  const sql=db();
  if(action==="low-value-decision"){
    assertRole(user,["Procurement Manager","Admin"]); const id=positiveId(payload.requestId,"request"); const decision=clean(payload.decision,30); if(!["approve","reject","return"].includes(decision)) throw new Error("Choose a valid decision."); const note=decision==="approve"?clean(payload.note,1200):reason(payload.note);
    return sql.begin(async tx=>{const rows=await tx<any[]>`SELECT pr.*,u.role requester_role FROM purchase_requests pr JOIN users u ON u.id=pr.requested_by WHERE pr.id=${id} FOR UPDATE`;const row=rows[0];if(!row)throw new Error("Request not found.");const limitRows=await tx<any[]>`SELECT amount FROM approval_policy_settings WHERE policy_key='procurement_manager_approval_limit' LIMIT 1`;const limit=Number(limitRows[0]?.amount||100000);if(Number(row.estimated_amount||0)>limit)throw new Error("This request exceeds the Procurement Manager approval limit.");if(row.requester_role==='Procurement Manager')throw new Error("Segregation of duties requires Approver / MD to decide Procurement Manager-originated requests.");
      const old=String(row.status||""); const status=decision==="approve"?"Approved":decision==="reject"?"Rejected":"Returned for Correction"; const next=decision==="approve"?"finance":"facility_manager"; const paymentStatus=decision==="approve"?"Approved for Payment":row.payment_status;
      await tx`UPDATE purchase_requests SET status=${status},next_role=${next},payment_status=${paymentStatus},approved_at=${decision==="approve"?new Date().toISOString():row.approved_at},approved_by_user_id=${decision==="approve"?user.id:row.approved_by_user_id},approved_by_role=${decision==="approve"?user.role:row.approved_by_role},approval_mode=${decision==="approve"?'Procurement Manager Low-Value Approval':row.approval_mode},updated_at=NOW() WHERE id=${id}`;
      await tx`INSERT INTO approval_history (entity_type,entity_id,action,status_before,status_after,reason,user_id,approved_by_user_id,approved_by_role,approval_mode,note,created_at) VALUES ('Purchase Request',${id},${decision==="approve"?'Approved':'Decision'},${old},${status},${note||decision},${user.id},${user.id},${user.role},'Procurement Manager Low-Value Approval',${note||decision},NOW())`;
      await workflow(tx,user,"Purchase Request",id,`Low-Value ${decision}`,status,note||decision); await evidence(tx,user,{action:`Low-Value ${decision}`,entityType:"Purchase Request",entityId:id,entityReference:row.request_no,before:{status:old,next_role:row.next_role},after:{status,next_role:next,payment_status:paymentStatus},note:note||decision,relatedUserId:row.facility_manager_user_id});
      if(row.facility_manager_user_id)await notifyUser(tx,Number(row.facility_manager_user_id),`Request ${status}`,`${row.request_no} is now ${status}.`,"Purchase Request",id,decision==="approve"?"Approved / Accepted Requests":"Returned Requests",decision==="approve"?"Normal":"High"); if(decision==="approve")await notifyRole(tx,"Finance","Request approved for payment",`${row.request_no} is approved and ready for Finance.`,"Purchase Request",id,"Approved for Payment","High"); return {id,status};});
  }

  if(action==="create-po"){
    assertRole(user,["Procurement Manager","Admin"]); const requestId=positiveId(payload.requestId,"request");
    return sql.begin(async tx=>{const rows=await tx<any[]>`SELECT * FROM purchase_requests WHERE id=${requestId} FOR UPDATE`;const r=rows[0];if(!r)throw new Error("Request not found.");if(r.linked_po_id)throw new Error("This request already has a linked purchase order.");if(!["Approved","Vendor Recommendation Approved","Accepted by Procurement Manager","Payment Approved"].includes(String(r.status||"")))throw new Error(`A commercial PO cannot be created from status '${r.status||"Unknown"}'.`);const vendorId=Number(payload.vendorId||r.selected_vendor_id||0);if(!vendorId)throw new Error("Select the approved vendor before creating the PO.");const v=await tx<any[]>`SELECT id,name FROM vendors WHERE id=${vendorId} LIMIT 1`;if(!v[0])throw new Error("Vendor not found.");const poNo=ref("PO");const total=money(payload.totalAmount??r.estimated_amount,"PO total");const expected=clean(payload.expectedDeliveryDate,20)||null;const policy=await tx<any[]>`SELECT amount FROM approval_policy_settings WHERE policy_key='procurement_manager_approval_limit' LIMIT 1`;const limit=Number(policy[0]?.amount||100000);const auto=total<=limit;const status=auto?"Approved":"Pending Approval";const next=auto?"procurement_manager":"approver";const po=await tx<any[]>`INSERT INTO purchase_orders (po_no,request_id,vendor_id,po_date,expected_delivery_date,status,total_amount,approved_by,payment_status,receiving_status,created_by,created_at,updated_at,approved_by_role,approval_mode,next_role) VALUES (${poNo},${requestId},${vendorId},CURRENT_DATE,${expected},${status},${total},${auto?user.id:null},'Pending','Pending Receipt',${user.id},NOW(),NOW(),${auto?user.role:null},${auto?'Procurement Manager Low-Value PO Approval':null},${next}) RETURNING id`;const poId=Number(po[0].id);
      const items=await tx<any[]>`SELECT * FROM purchase_request_items WHERE request_id=${requestId} ORDER BY id`;for(const item of items){await tx`INSERT INTO purchase_order_items (po_id,item_name,description,quantity,unit_price,total,category,created_at) VALUES (${poId},${item.item_name},${item.description},${item.quantity},${item.unit_price},${item.total},${item.category},NOW())`;}
      await tx`UPDATE purchase_requests SET linked_po_id=${poId},status='PO Created',next_role=${next},updated_at=NOW() WHERE id=${requestId}`;await workflow(tx,user,"Purchase Order",poId,"PO Created",status,`Created from ${r.request_no} for ${v[0].name}`);await evidence(tx,user,{action:"Purchase Order Created",entityType:"Purchase Order",entityId:poId,entityReference:poNo,after:{request_id:requestId,vendor_id:vendorId,total_amount:total,status,next_role:next},note:clean(payload.note,1500)||`Commercial PO created for ${r.request_no}`}); if(!auto)await notifyRole(tx,"Approver","Purchase order requires approval",`${poNo} for ${r.request_no} requires approval.`,"Purchase Order",poId,"PO Approval","High");return {poId,poNo,status};});
  }

  if(action==="release-po"){
    assertRole(user,["Procurement Manager","Admin"]);const poId=positiveId(payload.poId,"purchase order");const note=clean(payload.note,1500)||"Commercial PO released to vendor and Logistics";
    return sql.begin(async tx=>{const rows=await tx<any[]>`SELECT po.*,pr.request_no FROM purchase_orders po LEFT JOIN purchase_requests pr ON pr.id=po.request_id WHERE po.id=${poId} FOR UPDATE`;const po=rows[0];if(!po)throw new Error("Purchase order not found.");if(String(po.status)!=='Approved')throw new Error("Only an approved purchase order can be released.");await tx`UPDATE purchase_orders SET status='Sent to Vendor',sent_to_vendor_date=CURRENT_DATE,released_to_logistics_at=NOW(),released_to_logistics_by=${user.id},logistics_status='Awaiting Handover',next_role='logistics_officer',updated_at=NOW() WHERE id=${poId}`;if(po.request_id)await tx`UPDATE purchase_requests SET status='Sent to Vendor',next_role='logistics_officer',updated_at=NOW() WHERE id=${po.request_id}`;await workflow(tx,user,"Purchase Order",poId,"Released to Vendor / Logistics","Sent to Vendor",note);await evidence(tx,user,{action:"Purchase Order Released",entityType:"Purchase Order",entityId:poId,entityReference:po.po_no,before:{status:po.status},after:{status:"Sent to Vendor",logistics_status:"Awaiting Handover"},note});await notifyRole(tx,"Logistics Officer","PO released to Logistics",`${po.po_no} is ready for delivery handover.`,"Purchase Order",poId,"PO Delivery Handover","High");return {poId,status:"Sent to Vendor"};});
  }

  if(action==="vendor-save"){
    assertRole(user,["Procurement Manager","Admin"]);const id=Number(payload.vendorId||0);const name=clean(payload.name,180);if(name.length<2)throw new Error("Vendor name is required.");const values={category:clean(payload.category,160)||null,phone:clean(payload.phone,80)||null,email:clean(payload.email,180)||null,address:clean(payload.address,500)||null,taxId:clean(payload.taxId,120)||null,rating:Math.max(0,Math.min(5,Number(payload.rating||0))),status:clean(payload.status,60)||"Active"};
    return sql.begin(async tx=>{if(id){const old=(await tx<any[]>`SELECT id,name,category,phone,email,address,tax_id,rating,status FROM vendors WHERE id=${id} FOR UPDATE`)[0];if(!old)throw new Error("Vendor not found.");await tx`UPDATE vendors SET name=${name},category=${values.category},phone=${values.phone},email=${values.email},address=${values.address},tax_id=${values.taxId},rating=${values.rating},status=${values.status},updated_at=NOW() WHERE id=${id}`;await evidence(tx,user,{action:"Vendor Updated",entityType:"Vendor",entityId:id,entityReference:name,before:old,after:{name,...values},note:clean(payload.note,1200)||"Vendor master record updated"});return {vendorId:id};}
      const row=await tx<any[]>`INSERT INTO vendors (name,category,phone,email,address,tax_id,rating,completed_orders,total_spend,rejection_count,status,created_at,updated_at) VALUES (${name},${values.category},${values.phone},${values.email},${values.address},${values.taxId},${values.rating},0,0,0,${values.status},NOW(),NOW()) RETURNING id`;const vendorId=Number(row[0].id);await evidence(tx,user,{action:"Vendor Created",entityType:"Vendor",entityId:vendorId,entityReference:name,after:{name,...values},note:clean(payload.note,1200)||"Vendor added to supplier register"});return {vendorId};});
  }

  if(action==="gateway-create"){
    assertRole(user,["Facility Manager","Admin"]);const department=clean(payload.department,180);const movementType=clean(payload.movementType,120);const purpose=reason(payload.purpose);const items=Array.isArray(payload.items)?payload.items:[];if(!department||!movementType)throw new Error("Department and movement type are required.");if(!items.length)throw new Error("Add at least one item to the gateway pass.");const pass=ref("GP");
    return sql.begin(async tx=>{const row=await tx<any[]>`INSERT INTO gateway_passes (pass_number,facility_manager_user_id,department,movement_type,purpose,origin_location,destination,expected_movement_date,expected_return_date,vehicle_number,driver_name,driver_phone,receiver_name,receiver_organization,status,next_role,created_at,updated_at) VALUES (${pass},${user.id},${department},${movementType},${purpose},${clean(payload.originLocation,250)||null},${clean(payload.destination,250)||null},${clean(payload.expectedMovementDate,20)||null},${clean(payload.expectedReturnDate,20)||null},${clean(payload.vehicleNumber,80)||null},${clean(payload.driverName,160)||null},${clean(payload.driverPhone,80)||null},${clean(payload.receiverName,160)||null},${clean(payload.receiverOrganization,180)||null},'Draft','facility_manager',NOW(),NOW()) RETURNING id`;const id=Number(row[0].id);for(const item of items.slice(0,100)){const desc=clean(item.description,500);if(!desc)continue;await tx`INSERT INTO gateway_pass_items (gateway_pass_id,item_description,item_category,quantity,unit_of_measure,quality_condition,estimated_value,serial_number,asset_tag,fragility_status,handling_instruction,remarks,created_at,colour) VALUES (${id},${desc},${clean(item.category,120)||null},${money(item.quantity||1,"quantity")},${clean(item.unit,60)||'Unit'},${clean(item.condition,80)||'Good'},${money(item.estimatedValue||0,"estimated value")},${clean(item.serialNumber,120)||null},${clean(item.assetTag,120)||null},${clean(item.fragility,80)||'Normal'},${clean(item.handlingInstruction,400)||null},${clean(item.remarks,400)||null},NOW(),${clean(item.colour,80)||null})`;}
      await workflow(tx,user,"Gateway Pass",id,"Gateway Pass Draft Created","Draft",purpose);await evidence(tx,user,{action:"Gateway Pass Created",entityType:"Gateway Pass",entityId:id,entityReference:pass,after:{department,movement_type:movementType,status:"Draft",item_count:items.length},note:purpose});return {gatewayPassId:id,passNumber:pass};});
  }

  if(action==="gateway-submit"){
    assertRole(user,["Facility Manager","Admin"]);const id=positiveId(payload.gatewayPassId,"gateway pass");return sql.begin(async tx=>{const gp=(await tx<any[]>`SELECT * FROM gateway_passes WHERE id=${id} FOR UPDATE`)[0];if(!gp)throw new Error("Gateway pass not found.");if(user.role!=="Admin"&&Number(gp.facility_manager_user_id)!==user.id)throw new Error("You can submit only your own gateway passes.");if(!["Draft","Returned for Correction"].includes(String(gp.status||"")))throw new Error("This gateway pass is not ready for submission.");await tx`UPDATE gateway_passes SET status='Submitted',submitted_at=NOW(),next_role='procurement_manager',updated_at=NOW() WHERE id=${id}`;await workflow(tx,user,"Gateway Pass",id,"Submitted","Submitted",clean(payload.note,1000)||"Submitted for Procurement Manager review");await evidence(tx,user,{action:"Gateway Pass Submitted",entityType:"Gateway Pass",entityId:id,entityReference:gp.pass_number,before:{status:gp.status},after:{status:"Submitted",next_role:"procurement_manager"},note:clean(payload.note,1000)||"Submitted for review"});await notifyRole(tx,"Procurement Manager","Gateway pass awaiting review",`${gp.pass_number} requires Procurement Manager review.`,"Gateway Pass",id,"Gateway Pass Review","High");return {id,status:"Submitted"};});
  }

  if(action==="gateway-review"){
    assertRole(user,["Procurement Manager","Admin"]);const id=positiveId(payload.gatewayPassId,"gateway pass");const decision=clean(payload.decision,30);if(!["forward","return","reject"].includes(decision))throw new Error("Choose a valid review decision.");const note=reason(payload.note);
    return sql.begin(async tx=>{const gp=(await tx<any[]>`SELECT * FROM gateway_passes WHERE id=${id} FOR UPDATE`)[0];if(!gp)throw new Error("Gateway pass not found.");if(!["Submitted","Pending Procurement Manager / Approver Review"].includes(String(gp.status||"")))throw new Error("This gateway pass is not awaiting Procurement review.");const status=decision==="forward"?"Pending Procurement Manager / Approver Review":decision==="return"?"Returned for Correction":"Rejected";const next=decision==="forward"?"approver":decision==="return"?"facility_manager":null;await tx`UPDATE gateway_passes SET status=${status},next_role=${next},reviewed_by_user_id=${user.id},reviewed_at=NOW(),procurement_review_note=${note},rejected_at=${decision==="reject"?new Date().toISOString():gp.rejected_at},rejected_by_user_id=${decision==="reject"?user.id:gp.rejected_by_user_id},rejection_reason=${decision==="reject"?note:gp.rejection_reason},updated_at=NOW() WHERE id=${id}`;await tx`INSERT INTO gateway_pass_approvals (gateway_pass_id,approver_user_id,approver_role,decision,note,created_at) VALUES (${id},${user.id},${user.role},${decision},${note},NOW())`;await workflow(tx,user,"Gateway Pass",id,`Procurement ${decision}`,status,note);await evidence(tx,user,{action:`Gateway Pass Procurement ${decision}`,entityType:"Gateway Pass",entityId:id,entityReference:gp.pass_number,before:{status:gp.status},after:{status,next_role:next},note});if(decision==="forward")await notifyRole(tx,"Approver","Gateway pass requires final approval",`${gp.pass_number} passed Procurement review.`,"Gateway Pass",id,"Gateway Pass Approval","High");else if(gp.facility_manager_user_id)await notifyUser(tx,Number(gp.facility_manager_user_id),`Gateway pass ${status}`,`${gp.pass_number}: ${note}`,"Gateway Pass",id,"Gateway Pass","High");return {id,status};});
  }

  if(action==="gateway-generate"){
    assertRole(user,["Facility Manager","Admin"]);const id=positiveId(payload.gatewayPassId,"gateway pass");return sql.begin(async tx=>{const gp=(await tx<any[]>`SELECT * FROM gateway_passes WHERE id=${id} FOR UPDATE`)[0];if(!gp)throw new Error("Gateway pass not found.");if(user.role!=="Admin"&&Number(gp.facility_manager_user_id)!==user.id)throw new Error("You can generate only your own approved gateway passes.");if(!["Approved","Generated","Downloaded"].includes(String(gp.status||"")))throw new Error("Only an approved gateway pass can be generated.");const path=`/api/gateway-pass/${id}/pdf`;await tx`UPDATE gateway_passes SET status='Generated',generated_at=COALESCE(generated_at,NOW()),generated_file_path=${path},next_role='facility_manager',updated_at=NOW() WHERE id=${id}`;await workflow(tx,user,"Gateway Pass",id,"Generated","Generated","Gateway pass PDF generated");await evidence(tx,user,{action:"Gateway Pass Generated",entityType:"Gateway Pass",entityId:id,entityReference:gp.pass_number,before:{status:gp.status},after:{status:"Generated",generated_file_path:path},note:"Approved gateway pass generated for controlled download"});return {id,status:"Generated",downloadUrl:path};});
  }

  if(action==="thread-message"){
    assertRole(user,["Facility Manager","Procurement Manager","Admin"]);const threadId=positiveId(payload.threadId,"thread");const message=reason(payload.message);return sql.begin(async tx=>{const thread=(await tx<any[]>`SELECT * FROM collaboration_threads WHERE id=${threadId} FOR UPDATE`)[0];if(!thread)throw new Error("Shared thread not found.");if(user.role==="Facility Manager"&&Number(thread.facility_manager_user_id)!==user.id)throw new Error("This thread is not assigned to you.");if(user.role==="Procurement Manager"&&Number(thread.procurement_manager_user_id)!==user.id)throw new Error("This thread is not assigned to you.");const row=await tx<any[]>`INSERT INTO collaboration_messages (thread_id,sender_user_id,message_text,is_private,created_at) VALUES (${threadId},${user.id},${message},1,NOW()) RETURNING id`;await tx`UPDATE collaboration_threads SET updated_at=NOW() WHERE id=${threadId}`;const target=user.role==="Facility Manager"?Number(thread.procurement_manager_user_id):Number(thread.facility_manager_user_id);if(target)await notifyUser(tx,target,"New procurement thread message",message.slice(0,180),"Collaboration Thread",threadId,user.role==="Facility Manager"?"Utility Head / Facility Head Inbox":"Shared Thread with Procurement Manager");await evidence(tx,user,{action:"Shared Thread Message",entityType:"Collaboration Thread",entityId:threadId,after:{message_id:Number(row[0].id),message_length:message.length},note:"Private collaboration message recorded"});return {messageId:Number(row[0].id)};});
  }

  if(action==="availability-create"){
    assertRole(user,["Procurement Manager","Approver","Admin"]);const start=clean(payload.startDate,20);const end=clean(payload.endDate,20);if(!start||!end||end<start)throw new Error("Enter a valid away-date range.");const why=reason(payload.reason);const delegateId=payload.delegateUserId?positiveId(payload.delegateUserId,"delegate"):null;return sql.begin(async tx=>{const row=await tx<any[]>`INSERT INTO user_availability (user_id,role,status,away_start_date,away_end_date,reason,handover_note,recommended_delegate_role,recommended_delegate_user_id,urgency,admin_review_status,created_at,updated_at) VALUES (${user.id},${user.role},'Away Notice',${start},${end},${why},${clean(payload.handoverNote,1500)||null},${clean(payload.delegateRole,80)||null},${delegateId},${clean(payload.urgency,40)||'Normal'},'Pending',NOW(),NOW()) RETURNING id`;const id=Number(row[0].id);await evidence(tx,user,{action:"Availability Notice Submitted",entityType:"User Availability",entityId:id,entityReference:user.username,after:{away_start_date:start,away_end_date:end,delegate_user_id:delegateId,urgency:clean(payload.urgency,40)||'Normal'},note:why});await notifyRole(tx,"Admin","Availability / delegation request",`${user.fullName} submitted an away notice for ${start} to ${end}.`,"User Availability",id,"Availability & Delegation Requests","High");return {id};});
  }

  if(action==="close-request"){
    assertRole(user,["Procurement Manager","Admin"]);const id=positiveId(payload.requestId,"request");const note=reason(payload.note);return sql.begin(async tx=>{const r=(await tx<any[]>`SELECT * FROM purchase_requests WHERE id=${id} FOR UPDATE`)[0];if(!r)throw new Error("Request not found.");if(user.role!=="Admin"&&r.assigned_procurement_manager_id&&Number(r.assigned_procurement_manager_id)!==user.id)throw new Error("This request is assigned to another Procurement Manager.");const paid=String(r.payment_status||"")==="Paid"||String(r.status||"")==="Paid"||Boolean(r.paid_at);if(!paid)throw new Error("Only a paid procurement can be closed.");await tx`UPDATE purchase_requests SET status='Closed',next_role=NULL,completed_at=COALESCE(completed_at,NOW()),completed_by_user_id=${user.id},updated_at=NOW() WHERE id=${id}`;if(r.linked_po_id)await tx`UPDATE purchase_orders SET status=CASE WHEN receiving_status='Fully Received' THEN 'Closed' ELSE status END,next_role=NULL,updated_at=NOW() WHERE id=${r.linked_po_id}`;await workflow(tx,user,"Purchase Request",id,"Post-Payment Closure","Closed",note);await evidence(tx,user,{action:"Post-Payment Closure",entityType:"Purchase Request",entityId:id,entityReference:r.request_no,before:{status:r.status,next_role:r.next_role},after:{status:"Closed",next_role:null},note});if(r.facility_manager_user_id)await notifyUser(tx,Number(r.facility_manager_user_id),"Procurement closed",`${r.request_no} has been completed and closed.`,"Purchase Request",id,"Approved / Accepted Requests");return {id,status:"Closed"};});
  }

  if(action==="invoice-create"){
    assertRole(user,["Finance","Admin"]);const invoiceNo=clean(payload.invoiceNo,120)||ref("INV");const poId=payload.poId?positiveId(payload.poId,"PO"):null;const requestId=payload.requestId?positiveId(payload.requestId,"request"):null;const vendorId=payload.vendorId?positiveId(payload.vendorId,"vendor"):null;const amount=money(payload.amount,"invoice amount");const tax=money(payload.taxAmount||0,"tax amount");const total=money(payload.totalAmount??amount+tax,"invoice total");const file=filePayload(payload.file);return sql.begin(async tx=>{const dup=await tx<any[]>`SELECT id FROM invoices WHERE lower(invoice_no)=lower(${invoiceNo}) LIMIT 1`;if(dup[0])throw new Error("An invoice with this number already exists.");const row=await tx<any[]>`INSERT INTO invoices (invoice_no,po_id,vendor_id,invoice_date,amount,tax_amount,total_amount,file_path,file_hash,match_status,status,uploaded_by,created_at,invoice_type,document_stage,supplier_invoice_no,due_date,payment_terms,billing_address,shipping_address,subtotal,discount_amount,balance_due,linked_request_id,approval_status,interface_mode) VALUES (${invoiceNo},${poId},${vendorId},${clean(payload.invoiceDate,20)||new Date().toISOString().slice(0,10)},${amount},${tax},${total},${file?.locator||null},${file?.checksum||null},${clean(payload.matchStatus,80)||'Pending Match'},${clean(payload.status,80)||'Finance Review'},${user.id},NOW(),${clean(payload.invoiceType,80)||'Supplier Invoice'},'Finance',${clean(payload.supplierInvoiceNo,120)||invoiceNo},${clean(payload.dueDate,20)||null},${clean(payload.paymentTerms,200)||null},${clean(payload.billingAddress,400)||null},${clean(payload.shippingAddress,400)||null},${money(payload.subtotal??amount,"subtotal")},${money(payload.discountAmount||0,"discount")},${money(payload.balanceDue??total,"balance due")},${requestId},'Pending', 'Next.js') RETURNING id`;const id=Number(row[0].id);await evidence(tx,user,{action:"Invoice Recorded",entityType:"Invoice",entityId:id,entityReference:invoiceNo,after:{po_id:poId,request_id:requestId,vendor_id:vendorId,total_amount:total,file_checksum:file?.checksum||null},note:clean(payload.note,1500)||"Invoice recorded by Finance"});return {invoiceId:id,invoiceNo};});
  }

  if(action==="expense-create"){
    assertRole(user,["Finance","Admin"]);const no=ref("EXP");const amount=money(payload.amount,"expense amount");const file=filePayload(payload.file);return sql.begin(async tx=>{const row=await tx<any[]>`INSERT INTO expenses (expense_no,expense_date,category,description,vendor_id,amount,payment_method,project_department,status,receipt_path,receipt_hash,receipt_no,invoice_no,tax_amount,linked_po_id,invoice_match_status,duplicate_warning,requested_by,approved_by,approved_at,notes,created_at,document_kind) VALUES (${no},${clean(payload.expenseDate,20)||new Date().toISOString().slice(0,10)},${clean(payload.category,120)||'Other'},${reason(payload.description)},${payload.vendorId?positiveId(payload.vendorId,"vendor"):null},${amount},${clean(payload.paymentMethod,80)||'Bank Transfer'},${clean(payload.departmentProject,180)||null},${clean(payload.status,80)||'Recorded'},${file?.locator||null},${file?.checksum||null},${clean(payload.receiptNo,120)||null},${clean(payload.invoiceNo,120)||null},${money(payload.taxAmount||0,"tax amount")},${payload.poId?positiveId(payload.poId,"PO"):null},${clean(payload.invoiceMatchStatus,80)||'Not Matched'},FALSE,${user.id},${clean(payload.status,80)==='Approved'?user.id:null},${clean(payload.status,80)==='Approved'?new Date().toISOString():null},${clean(payload.note,1500)||null},NOW(),${clean(payload.documentKind,80)||'Expense'}) RETURNING id`;const id=Number(row[0].id);await evidence(tx,user,{action:"Expense Recorded",entityType:"Expense",entityId:id,entityReference:no,after:{amount,category:clean(payload.category,120)||'Other',file_checksum:file?.checksum||null},note:clean(payload.note,1500)||"Finance expense recorded"});return {expenseId:id,expenseNo:no};});
  }

  if(action==="cash-advance-create"){
    assertRole(user,["Finance","Admin"]);const no=ref("ADV");const amount=money(payload.amount,"advance amount");return sql.begin(async tx=>{const row=await tx<any[]>`INSERT INTO cash_advances (advance_no,date_collected,employee_name,amount_collected,purpose,status,created_by,due_date,created_at) VALUES (${no},${clean(payload.dateCollected,20)||new Date().toISOString().slice(0,10)},${reason(payload.employeeName)},${amount},${reason(payload.purpose)},'Open',${user.id},${clean(payload.dueDate,20)||null},NOW()) RETURNING id`;const id=Number(row[0].id);await evidence(tx,user,{action:"Cash Advance Created",entityType:"Cash Advance",entityId:id,entityReference:no,after:{employee_name:clean(payload.employeeName,180),amount_collected:amount,due_date:clean(payload.dueDate,20)||null},note:clean(payload.note,1200)||"Cash advance issued"});return {advanceId:id,advanceNo:no};});
  }

  if(action==="cash-advance-expense"){
    assertRole(user,["Finance","Admin"]);const advanceId=positiveId(payload.advanceId,"cash advance");const amount=money(payload.amount,"expense amount");const file=filePayload(payload.file);return sql.begin(async tx=>{const adv=(await tx<any[]>`SELECT * FROM cash_advances WHERE id=${advanceId} FOR UPDATE`)[0];if(!adv)throw new Error("Cash advance not found.");if(String(adv.status||"")==='Closed')throw new Error("This cash advance is closed.");const row=await tx<any[]>`INSERT INTO advance_expenses (advance_id,spent_date,description,category,amount,receipt_path,receipt_hash,created_at) VALUES (${advanceId},${clean(payload.spentDate,20)||new Date().toISOString().slice(0,10)},${reason(payload.description)},${clean(payload.category,120)||'Other'},${amount},${file?.locator||null},${file?.checksum||null},NOW()) RETURNING id`;await evidence(tx,user,{action:"Cash Advance Expense Added",entityType:"Cash Advance",entityId:advanceId,entityReference:adv.advance_no,after:{advance_expense_id:Number(row[0].id),amount,file_checksum:file?.checksum||null},note:clean(payload.note,1200)||"Advance expenditure recorded"});return {id:Number(row[0].id)};});
  }

  if(action==="cash-advance-close"){
    assertRole(user,["Finance","Admin"]);const advanceId=positiveId(payload.advanceId,"cash advance");const note=reason(payload.note);return sql.begin(async tx=>{const adv=(await tx<any[]>`SELECT ca.*,COALESCE((SELECT SUM(amount) FROM advance_expenses WHERE advance_id=ca.id),0) spent FROM cash_advances ca WHERE ca.id=${advanceId} FOR UPDATE`)[0];if(!adv)throw new Error("Cash advance not found.");await tx`UPDATE cash_advances SET status='Closed',approved_by=${user.id},approved_at=NOW() WHERE id=${advanceId}`;await evidence(tx,user,{action:"Cash Advance Closed",entityType:"Cash Advance",entityId:advanceId,entityReference:adv.advance_no,before:{status:adv.status},after:{status:"Closed",spent_amount:Number(adv.spent||0),balance:Number(adv.amount_collected||0)-Number(adv.spent||0)},note});return {advanceId,status:"Closed"};});
  }

  if(action==="document-upload"){
    const file=filePayload(payload.file);if(!file)throw new Error("Choose a file to upload.");const docType=clean(payload.documentType,120)||"Supporting Document";const title=clean(payload.title,180)||file.fileName;const note=clean(payload.note,1200)||null;const context=clean(payload.context,60)||"procurement";const entityId=payload.entityId?positiveId(payload.entityId,"linked record"):null;
    if(context==="logistics")assertRole(user,["Logistics Officer","Procurement Manager","Admin"]);else if(context==="vendor")assertRole(user,["Procurement Manager","Admin"]);else if(context==="receipt")assertRole(user,["Finance","Admin"]);else assertRole(user,["Facility Manager","Procurement Manager","Finance","Admin"]);
    return sql.begin(async tx=>{let id=0;let source="Imported Document";
      if(context==="logistics"){const row=await tx<any[]>`INSERT INTO logistics_documents (related_entity_type,related_entity_id,po_id,gateway_pass_id,document_type,file_name,file_path,notes,uploaded_by,created_at) VALUES (${clean(payload.relatedEntityType,80)||'Purchase Order'},${entityId},${payload.poId?positiveId(payload.poId,"PO"):null},${payload.gatewayPassId?positiveId(payload.gatewayPassId,"gateway pass"):null},${docType},${file.fileName},${file.locator},${note},${user.id},NOW()) RETURNING id`;id=Number(row[0].id);source="Logistics Document";}
      else if(context==="vendor"){const vendorId=positiveId(payload.vendorId||entityId,"vendor");const row=await tx<any[]>`INSERT INTO vendor_documents (vendor_id,title,document_type,file_path,file_hash,notes,uploaded_by,created_at) VALUES (${vendorId},${title},${docType},${file.locator},${file.checksum},${note},${user.id},NOW()) RETURNING id`;id=Number(row[0].id);source="Vendor Document";}
      else if(context==="receipt"){const no=clean(payload.receiptNo,120)||ref("REC");const row=await tx<any[]>`INSERT INTO receipt_records (receipt_no,receipt_type,payment_method,payment_date,vendor_id,payee_name,amount,currency,purpose,department_project,linked_invoice_id,linked_payment_id,linked_po_id,status,file_path,file_hash,notes,uploaded_by,created_at,updated_at,document_category,request_id,payment_id,original_file_name,mime_type,file_size_bytes,file_checksum,ocr_status,discrepancy_status,interface_mode) VALUES (${no},${docType},${clean(payload.paymentMethod,80)||null},${clean(payload.paymentDate,20)||new Date().toISOString().slice(0,10)},${payload.vendorId?positiveId(payload.vendorId,"vendor"):null},${clean(payload.payeeName,180)||null},${money(payload.amount||0,"receipt amount")},${clean(payload.currency,12)||'NGN'},${clean(payload.purpose,400)||null},${clean(payload.departmentProject,180)||null},${payload.invoiceId?positiveId(payload.invoiceId,"invoice"):null},${payload.paymentId?positiveId(payload.paymentId,"payment"):null},${payload.poId?positiveId(payload.poId,"PO"):null},'Recorded',${file.locator},${file.checksum},${note},${user.id},NOW(),NOW(),${docType},${payload.requestId?positiveId(payload.requestId,"request"):null},${payload.paymentId?positiveId(payload.paymentId,"payment"):null},${file.fileName},${file.mimeType},${file.bytes},${file.checksum},'Not Processed','None','Next.js') RETURNING id`;id=Number(row[0].id);source="Receipt";}
      else {const row=await tx<any[]>`INSERT INTO imported_legacy_documents (source_zip_name,original_path,file_name,file_path,file_hash,document_type,department_project,title,likely_date,likely_vendor,total_amount,import_status,confidence,linked_request_id,duplicate_warning,imported_by,created_at,updated_at,assigned_procurement_manager_id,facility_manager_user_id) VALUES ('Next.js Upload',${file.fileName},${file.fileName},${file.locator},${file.checksum},${docType},${clean(payload.departmentProject,180)||null},${title},${clean(payload.likelyDate,20)||null},${clean(payload.likelyVendor,180)||null},${money(payload.totalAmount||0,"document total")},'Imported',1,FALSE,${entityId},FALSE,${user.id},NOW(),NOW(),${user.role==='Procurement Manager'?user.id:null},${user.role==='Facility Manager'?user.id:null}) RETURNING id`;id=Number(row[0].id);}
      await evidence(tx,user,{action:"Document Uploaded",entityType:source,entityId:id,entityReference:title,after:{document_type:docType,file_name:file.fileName,file_size_bytes:file.bytes,file_checksum:file.checksum,linked_entity_id:entityId},note:note||"Document stored in the GCP-free Neon document register"});return {documentId:id,sourceType:source};});
  }

  if(action==="notification-read"){
    const id=payload.notificationId?positiveId(payload.notificationId,"notification"):null; if(id)await sql`UPDATE notifications SET is_read=TRUE,popup_shown=TRUE WHERE id=${id} AND (user_id=${user.id} OR (user_id IS NULL AND role=${user.role}))`;else await sql`UPDATE notifications SET is_read=TRUE,popup_shown=TRUE WHERE user_id=${user.id} OR (user_id IS NULL AND role=${user.role})`;return {ok:true};
  }

  throw new Error("Unsupported ProcureFlow parity action.");
}
