function pdfEscape(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)").replace(/[\r\n]+/g, " ");
}

const ASCII_REPLACEMENTS: Record<string, string> = {
  "₦": "NGN ",
  "–": "-",
  "—": "-",
  "→": "->",
  "•": "*",
};

function ascii(value: unknown) {
  return String(value ?? "")
    .normalize("NFKD")
    .replace(/[^\x20-\x7E]/g, (char) => ASCII_REPLACEMENTS[char] || "?");
}

function wrapLine(text: string, width = 88) {
  const words = ascii(text).split(/\s+/).filter(Boolean);
  if (!words.length) return [""];
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    if (!current) current = word;
    else if (`${current} ${word}`.length <= width) current += ` ${word}`;
    else {
      lines.push(current);
      current = word;
    }
  }
  if (current) lines.push(current);
  return lines;
}

export function simplePdf(title: string, rawLines: string[], footer = "Generated by ProcureFlow") {
  const lines = [title, "", ...rawLines].flatMap((line) => wrapLine(line));
  const pageCapacity = 47;
  const pages: string[][] = [];
  for (let i = 0; i < lines.length; i += pageCapacity) pages.push(lines.slice(i, i + pageCapacity));
  if (!pages.length) pages.push([title]);

  const objects: string[] = [];
  const pageIds: number[] = [];
  const contentIds: number[] = [];
  const catalogId = 1;
  const pagesId = 2;
  const fontId = 3;
  let nextId = 4;
  for (let i = 0; i < pages.length; i++) {
    pageIds.push(nextId++);
    contentIds.push(nextId++);
  }

  objects[catalogId] = `<< /Type /Catalog /Pages ${pagesId} 0 R >>`;
  objects[fontId] = `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`;
  objects[pagesId] = `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pages.length} >>`;

  pages.forEach((pageLines, pageIndex) => {
    const pageId = pageIds[pageIndex];
    const contentId = contentIds[pageIndex];
    const ops: string[] = ["BT", "/F1 11 Tf", "50 790 Td", "14 TL"];
    pageLines.forEach((line, index) => {
      if (index === 0 && pageIndex === 0) ops.push("/F1 16 Tf");
      ops.push(`(${pdfEscape(line)}) Tj`);
      ops.push("T*");
      if (index === 0 && pageIndex === 0) ops.push("/F1 11 Tf");
    });
    ops.push("T*", `(${pdfEscape(`${footer} | Page ${pageIndex + 1} of ${pages.length}`)}) Tj`, "ET");
    const stream = ops.join("\n");
    objects[contentId] = `<< /Length ${Buffer.byteLength(stream, "utf8")} >>\nstream\n${stream}\nendstream`;
    objects[pageId] = `<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${contentId} 0 R >>`;
  });

  let body = "%PDF-1.4\n";
  const offsets: number[] = [0];
  for (let id = 1; id < objects.length; id++) {
    offsets[id] = Buffer.byteLength(body, "utf8");
    body += `${id} 0 obj\n${objects[id]}\nendobj\n`;
  }
  const xref = Buffer.byteLength(body, "utf8");
  body += `xref\n0 ${objects.length}\n0000000000 65535 f \n`;
  for (let id = 1; id < objects.length; id++) body += `${String(offsets[id]).padStart(10, "0")} 00000 n \n`;
  body += `trailer\n<< /Size ${objects.length} /Root ${catalogId} 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.from(body, "utf8");
}

export function csvText(rows: Record<string, unknown>[]) {
  if (!rows.length) return "";
  const keys = Array.from(new Set(rows.flatMap((row) => Object.keys(row))));
  const cell = (value: unknown) => `"${String(value ?? "").replace(/"/g, '""')}"`;
  return [keys.map(cell).join(","), ...rows.map((row) => keys.map((key) => cell(row[key])).join(","))].join("\r\n");
}
